// Package client is a thin HTTP client over horsie's REST API.
//
// The wire types come from internal/horsieapi, generated by fluorite from
// horsie's .fl schemas — the same schemas the server and the web UI are built
// from, so a field rename cannot silently diverge here. This package adds only
// transport: base URL, auth, and turning a non-2xx into a typed error.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"
	"time"
)

// Client talks to one horsie server as one account.
type Client struct {
	baseURL string
	token   string
	http    *http.Client
}

// Error is a non-2xx response. Callers switch on Status to tell "gone" from
// "rejected" — a 404 during Read means Terraform should drop the resource from
// state, while a 409 during Delete means something still references it.
type Error struct {
	Status int
	Method string
	Path   string
	Body   string
}

func (e *Error) Error() string {
	if e.Body == "" {
		return fmt.Sprintf("%s %s: %d", e.Method, e.Path, e.Status)
	}
	return fmt.Sprintf("%s %s: %d: %s", e.Method, e.Path, e.Status, e.Body)
}

// IsNotFound reports whether err is a 404, which every Read treats as "removed
// outside Terraform" rather than as a failure.
func IsNotFound(err error) bool {
	var e *Error
	return errors.As(err, &e) && e.Status == http.StatusNotFound
}

// New returns a client for baseURL authenticating with an agent token.
//
// The token is a horsie agent token (`POST /api/device/tokens`), which is
// long-lived and revocable by label — the only credential horsie has that suits
// an unattended caller.
func New(baseURL, token string) *Client {
	return &Client{
		baseURL: strings.TrimRight(baseURL, "/"),
		token:   token,
		http:    &http.Client{Timeout: 60 * time.Second},
	}
}

// Do sends body (nil for none) to path and decodes the response into out (nil
// to discard it).
func (c *Client) Do(ctx context.Context, method, path string, body, out any) error {
	var reader io.Reader
	if body != nil {
		encoded, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("encode %s %s: %w", method, path, err)
		}
		reader = bytes.NewReader(encoded)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.baseURL+path, reader)
	if err != nil {
		return fmt.Errorf("build %s %s: %w", method, path, err)
	}
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.token != "" {
		req.Header.Set("Authorization", "Bearer "+c.token)
	}

	res, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("%s %s: %w", method, path, err)
	}
	defer res.Body.Close()

	if res.StatusCode < 200 || res.StatusCode >= 300 {
		// Bounded: an error body is a short JSON object, and a stray HTML error
		// page should not end up in a Terraform diagnostic in full.
		snippet, _ := io.ReadAll(io.LimitReader(res.Body, 4096))
		return &Error{
			Status: res.StatusCode,
			Method: method,
			Path:   path,
			Body:   strings.TrimSpace(string(snippet)),
		}
	}

	if out == nil {
		// Drain so the connection can be reused.
		_, _ = io.Copy(io.Discard, res.Body)
		return nil
	}
	if err := json.NewDecoder(res.Body).Decode(out); err != nil {
		return fmt.Errorf("decode %s %s: %w", method, path, err)
	}
	return nil
}
