// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Agent settings supplied at session creation.
type AgentSettings struct {
	Model         string    `json:"model"`
	AllowedTools  *[]string `json:"allowedTools,omitempty"`
	UsePlugins    *bool     `json:"usePlugins,omitempty"`
	MaxIterations *uint32   `json:"maxIterations,omitempty"`
	MaxRetries    *uint32   `json:"maxRetries,omitempty"`
	// Names of enabled MCP servers this session may call, namespaced
	// `mcp__<name>__<tool>`; absent → none.
	MCPServers *[]string `json:"mcpServers,omitempty"`
	// Memory spaces this session may read and write; absent → none, and the
	// memory_* tools are not offered.
	MemorySpaces *[]string `json:"memorySpaces,omitempty"`
	// Canonical thinking effort for this session, chosen from the model's
	// offered list. Absent → the model's configured default.
	ThinkingEffort *string `json:"thinkingEffort,omitempty"`
	// Cap on concurrently-active subagents in this session; absent → the
	// server's built-in default (8).
	MaxConcurrentSubagents *uint32 `json:"maxConcurrentSubagents,omitempty"`
}
