// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// AgentLogBodyVariant is implemented by every variant of AgentLogBody.
type AgentLogBodyVariant interface {
	isAgentLogBodyVariant()
}

type AgentLogBodyLLM struct {
	Value Message
}

func (AgentLogBodyLLM) isAgentLogBodyVariant() {}

type AgentLogBodyHook struct {
	Value HookEntry
}

func (AgentLogBodyHook) isAgentLogBodyVariant() {}

type AgentLogBodyLifecycle struct {
	Value LifecycleEvent
}

func (AgentLogBodyLifecycle) isAgentLogBodyVariant() {}

// What one log entry carries.
//
// Three arms, not eight: `AgentState::prompt_messages` is a match over this
// union, and a single `Lifecycle` arm mapping to nothing covers every
// lifecycle variant that will ever exist. Flattening the variants in here
// would make provider isolation a per-variant obligation a future addition
// could forget.
// AgentLogBody is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type AgentLogBody struct {
	Variant AgentLogBodyVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u AgentLogBody) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case AgentLogBodyLLM:
		return json.Marshal(struct {
			Type  string  `json:"type"`
			Value Message `json:"value"`
		}{"Llm", v.Value})
	case AgentLogBodyHook:
		return json.Marshal(struct {
			Type  string    `json:"type"`
			Value HookEntry `json:"value"`
		}{"Hook", v.Value})
	case AgentLogBodyLifecycle:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value LifecycleEvent `json:"value"`
		}{"Lifecycle", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: AgentLogBody has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown AgentLogBody variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *AgentLogBody) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Llm":
		var v Message
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentLogBodyLLM{Value: v}
		return nil
	case "Hook":
		var v HookEntry
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentLogBodyHook{Value: v}
		return nil
	case "Lifecycle":
		var v LifecycleEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentLogBodyLifecycle{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown AgentLogBody variant tag %q", envelope.Type)
	}
}
