// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// AgentInputVariant is implemented by every variant of AgentInput.
type AgentInputVariant interface {
	isAgentInputVariant()
}

type AgentInputUserMessage struct {
	Value UserMessageInput
}

func (AgentInputUserMessage) isAgentInputVariant() {}

type AgentInputToolResult struct {
	Value ToolResultInput
}

func (AgentInputToolResult) isAgentInputVariant() {}

type AgentInputToolResults struct {
	Value ToolResultsInput
}

func (AgentInputToolResults) isAgentInputVariant() {}

// The only valid inputs to Agent::run
// AgentInput is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type AgentInput struct {
	Variant AgentInputVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u AgentInput) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case AgentInputUserMessage:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value UserMessageInput `json:"value"`
		}{"UserMessage", v.Value})
	case AgentInputToolResult:
		return json.Marshal(struct {
			Type  string          `json:"type"`
			Value ToolResultInput `json:"value"`
		}{"ToolResult", v.Value})
	case AgentInputToolResults:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value ToolResultsInput `json:"value"`
		}{"ToolResults", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: AgentInput has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown AgentInput variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *AgentInput) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "UserMessage":
		var v UserMessageInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentInputUserMessage{Value: v}
		return nil
	case "ToolResult":
		var v ToolResultInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentInputToolResult{Value: v}
		return nil
	case "ToolResults":
		var v ToolResultsInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentInputToolResults{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown AgentInput variant tag %q", envelope.Type)
	}
}
