// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Invoke a preset: create a session from it and queue a first message.
type AgentInvokeRequest struct {
	// First user message; queued immediately after the session is created.
	Message string `json:"message"`
	// Optional session title.
	Name *string `json:"name,omitempty"`
}
