// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A machine token as listed in Settings. The secret itself appears exactly
// once, in `AgentTokenCreated` — only its hash is stored, so there is nothing
// to show later even if we wanted to.
type AgentTokenView struct {
	ID    string `json:"id"`
	Label string `json:"label"`
	// Unix epoch seconds.
	CreatedAt string `json:"createdAt"`
	// Unix epoch seconds, absent until the token is first used.
	LastUsedAt *string `json:"lastUsedAt,omitempty"`
}
