// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type AgentTokenCreateInput struct {
	// Which machine this token is for. Required: a wall of unlabelled secrets
	// is unrevokable in practice.
	Label string `json:"label"`
}
