// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One agent's current values. The subagent-only fields (`parent`, `label`,
// `task`, `output`, `error`) are absent for a session's main agent.
type AgentDocument struct {
	ID string `json:"id"`
	// Parent agent id; absent → rooted on whatever this session's primary
	// agent is: its main agent, or the step that spawned it.
	Parent *string `json:"parent,omitempty"`
	// A subagent's label, or the step a workflow agent ran.
	Label *string `json:"label,omitempty"`
	// The task a subagent was spawned to do.
	Task  *string `json:"task,omitempty"`
	Depth uint32  `json:"depth"`
	// What became of this agent. The same vocabulary the session's roster
	// speaks: "provisioning" | "running" | "idle" | "awaiting_input" |
	// "completed" | "failed" | "cancelled".
	Status string  `json:"status"`
	Output *string `json:"output,omitempty"`
	Error  *string `json:"error,omitempty"`
	// The agent's `task_list` tool state.
	Tasks []TaskItem `json:"tasks"`
	// Cumulative usage across this agent's completed turns.
	Usage UsageView `json:"usage"`
	// The most recently completed turn's own usage. Absent before the first.
	LastTurnUsage *Usage `json:"lastTurnUsage,omitempty"`
	// The last provider call's prompt size — what is loaded in context now.
	// Never summed across turns.
	ContextTokens uint32 `json:"contextTokens"`
	// The model's configured context window, when known. Attached by the HTTP
	// layer from model config — this one field is not agent state.
	ContextWindow *uint32 `json:"contextWindow,omitempty"`
	// The log position this document reflects.
	//
	// What makes reading this alongside the log safe rather than a race: a
	// consumer records the seq each value was last set from and applies an
	// update only if its seq is greater — whichever source it came from. A
	// boolean "a live frame has arrived" latch cannot express that, because it
	// cannot tell a document that is *ahead* of the fold from one behind it.
	AsOfSeq uint64 `json:"asOfSeq"`
}
