// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// An agent preset as shown to clients.
type AgentView struct {
	// Slug; the id of record, used in API paths and CLI invocations.
	Name        string `json:"name"`
	Description string `json:"description"`
	// Configured model alias.
	Model string `json:"model"`
	// Selected plugin-bundle (skill) names.
	Plugins []string `json:"plugins"`
	// Enabled MCP server names.
	MCPServers []string `json:"mcpServers"`
	// Memory spaces the session may read and write.
	MemorySpaces []string `json:"memorySpaces"`
	// Canonical thinking effort; absent → the model's configured default.
	ThinkingEffort *string `json:"thinkingEffort,omitempty"`
	// Unix epoch seconds.
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
