// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type AgentTokenCreated struct {
	// Shown once and never again.
	Token string         `json:"token"`
	View  AgentTokenView `json:"view"`
}
