// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Create or fully replace an agent preset. Omitted list fields default to
// empty; `description` defaults to "".
//
// Named `AgentPresetInput`, not `AgentInput`: fluorite resolves imported types
// by bare name across packages, so a second `AgentInput` would hijack
// `events`' reference to the agent-loop `agent.AgentInput`.
type AgentPresetInput struct {
	Name           string    `json:"name"`
	Description    *string   `json:"description,omitempty"`
	Model          string    `json:"model"`
	Plugins        *[]string `json:"plugins,omitempty"`
	MCPServers     *[]string `json:"mcpServers,omitempty"`
	MemorySpaces   *[]string `json:"memorySpaces,omitempty"`
	ThinkingEffort *string   `json:"thinkingEffort,omitempty"`
}
