// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Agent settings supplied at session creation.
type AgentSettings struct {
	Model         string    `json:"model"`
	AllowedTools  *[]string `json:"allowedTools,omitempty"`
	UsePlugins    *bool     `json:"usePlugins,omitempty"`
	MaxIterations *uint32   `json:"maxIterations,omitempty"`
	MaxRetries    *uint32   `json:"maxRetries,omitempty"`
	// Names of enabled MCP servers this session may call, namespaced
	// `mcp__<name>__<tool>`; absent → none.
	MCPServers *[]string `json:"mcpServers,omitempty"`
	// Memory spaces this session may read and write; absent → none, and the
	// memory_* tools are not offered.
	MemorySpaces *[]string `json:"memorySpaces,omitempty"`
	// Canonical thinking effort for this session, chosen from the model's
	// offered list. Absent → the model's configured default.
	ThinkingEffort *string `json:"thinkingEffort,omitempty"`
	// Cap on concurrently-active subagents in this session; absent → the
	// server's built-in default (8).
	MaxConcurrentSubagents *uint32 `json:"maxConcurrentSubagents,omitempty"`
	// Standing instructions this session's agent runs under, added to the
	// system prompt as its own section. Set from an agent preset, or directly
	// here; absent → none.
	Instructions *string `json:"instructions,omitempty"`
	// Whether this session summarises older history into a compaction
	// boundary once its context fills; absent → yes.
	//
	// A flag rather than a threshold: the share of the window at which
	// compacting is worthwhile is a property of the model, not of the
	// session, so it stays a server constant that can be retuned centrally
	// instead of a number frozen into everyone's saved settings. Has no
	// effect when the model's card declares no context window — there is
	// then nothing to be a share of.
	AutoCompact *bool `json:"autoCompact,omitempty"`
}
