// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// AgentEventVariant is implemented by every variant of AgentEvent.
type AgentEventVariant interface {
	isAgentEventVariant()
}

type AgentEventInputMessage struct {
	Value InputMessageEvent
}

func (AgentEventInputMessage) isAgentEventVariant() {}

type AgentEventMessageStart struct {
	Value MessageStartEvent
}

func (AgentEventMessageStart) isAgentEventVariant() {}

type AgentEventMessageStop struct {
	Value MessageStopEvent
}

func (AgentEventMessageStop) isAgentEventVariant() {}

type AgentEventMessageComplete struct {
	Value MessageCompleteEvent
}

func (AgentEventMessageComplete) isAgentEventVariant() {}

type AgentEventTextBlockStart struct {
	Value TextBlockStartEvent
}

func (AgentEventTextBlockStart) isAgentEventVariant() {}

type AgentEventTextChunk struct {
	Value TextChunkEvent
}

func (AgentEventTextChunk) isAgentEventVariant() {}

type AgentEventThinkingBlockStart struct {
	Value ThinkingBlockStartEvent
}

func (AgentEventThinkingBlockStart) isAgentEventVariant() {}

type AgentEventThinkingChunk struct {
	Value ThinkingChunkEvent
}

func (AgentEventThinkingChunk) isAgentEventVariant() {}

type AgentEventThinkingSignatureChunk struct {
	Value ThinkingSignatureChunkEvent
}

func (AgentEventThinkingSignatureChunk) isAgentEventVariant() {}

type AgentEventToolCallStart struct {
	Value ToolCallStartEvent
}

func (AgentEventToolCallStart) isAgentEventVariant() {}

type AgentEventToolCallInputDelta struct {
	Value ToolCallInputDeltaEvent
}

func (AgentEventToolCallInputDelta) isAgentEventVariant() {}

type AgentEventContentBlockStop struct {
	Value ContentBlockStopEvent
}

func (AgentEventContentBlockStop) isAgentEventVariant() {}

type AgentEventToolExecuting struct {
	Value ToolExecutingEvent
}

func (AgentEventToolExecuting) isAgentEventVariant() {}

type AgentEventToolComplete struct {
	Value ToolCompleteEvent
}

func (AgentEventToolComplete) isAgentEventVariant() {}

type AgentEventRunComplete struct {
	Value RunCompleteEvent
}

func (AgentEventRunComplete) isAgentEventVariant() {}

type AgentEventRunAborted struct {
	Value RunAbortedEvent
}

func (AgentEventRunAborted) isAgentEventVariant() {}

type AgentEventCompacted struct {
	Value CompactedEvent
}

func (AgentEventCompacted) isAgentEventVariant() {}

type AgentEventCompactionSkipped struct {
	Value CompactionSkippedEvent
}

func (AgentEventCompactionSkipped) isAgentEventVariant() {}

// All events emitted during agent execution.
//
// Flow per assistant turn:
// InputMessage (once, at the start of run)
// MessageStart → ( block )* → MessageStop → MessageComplete
// where each block is one of:
// TextBlockStart     → TextChunk*                              → ContentBlockStop
// ThinkingBlockStart → (ThinkingChunk | ThinkingSignatureChunk)* → ContentBlockStop
// ToolCallStart      → ToolCallInputDelta*                     → ContentBlockStop
// ToolExecuting → ToolComplete  (one pair per tool call)
// RunComplete   (or RunAborted, if the run ended in an error instead)
// AgentEvent is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type AgentEvent struct {
	Variant AgentEventVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u AgentEvent) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case AgentEventInputMessage:
		return json.Marshal(struct {
			Type  string            `json:"type"`
			Value InputMessageEvent `json:"value"`
		}{"InputMessage", v.Value})
	case AgentEventMessageStart:
		return json.Marshal(struct {
			Type  string            `json:"type"`
			Value MessageStartEvent `json:"value"`
		}{"MessageStart", v.Value})
	case AgentEventMessageStop:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value MessageStopEvent `json:"value"`
		}{"MessageStop", v.Value})
	case AgentEventMessageComplete:
		return json.Marshal(struct {
			Type  string               `json:"type"`
			Value MessageCompleteEvent `json:"value"`
		}{"MessageComplete", v.Value})
	case AgentEventTextBlockStart:
		return json.Marshal(struct {
			Type  string              `json:"type"`
			Value TextBlockStartEvent `json:"value"`
		}{"TextBlockStart", v.Value})
	case AgentEventTextChunk:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value TextChunkEvent `json:"value"`
		}{"TextChunk", v.Value})
	case AgentEventThinkingBlockStart:
		return json.Marshal(struct {
			Type  string                  `json:"type"`
			Value ThinkingBlockStartEvent `json:"value"`
		}{"ThinkingBlockStart", v.Value})
	case AgentEventThinkingChunk:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value ThinkingChunkEvent `json:"value"`
		}{"ThinkingChunk", v.Value})
	case AgentEventThinkingSignatureChunk:
		return json.Marshal(struct {
			Type  string                      `json:"type"`
			Value ThinkingSignatureChunkEvent `json:"value"`
		}{"ThinkingSignatureChunk", v.Value})
	case AgentEventToolCallStart:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value ToolCallStartEvent `json:"value"`
		}{"ToolCallStart", v.Value})
	case AgentEventToolCallInputDelta:
		return json.Marshal(struct {
			Type  string                  `json:"type"`
			Value ToolCallInputDeltaEvent `json:"value"`
		}{"ToolCallInputDelta", v.Value})
	case AgentEventContentBlockStop:
		return json.Marshal(struct {
			Type  string                `json:"type"`
			Value ContentBlockStopEvent `json:"value"`
		}{"ContentBlockStop", v.Value})
	case AgentEventToolExecuting:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value ToolExecutingEvent `json:"value"`
		}{"ToolExecuting", v.Value})
	case AgentEventToolComplete:
		return json.Marshal(struct {
			Type  string            `json:"type"`
			Value ToolCompleteEvent `json:"value"`
		}{"ToolComplete", v.Value})
	case AgentEventRunComplete:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value RunCompleteEvent `json:"value"`
		}{"RunComplete", v.Value})
	case AgentEventRunAborted:
		return json.Marshal(struct {
			Type  string          `json:"type"`
			Value RunAbortedEvent `json:"value"`
		}{"RunAborted", v.Value})
	case AgentEventCompacted:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value CompactedEvent `json:"value"`
		}{"Compacted", v.Value})
	case AgentEventCompactionSkipped:
		return json.Marshal(struct {
			Type  string                 `json:"type"`
			Value CompactionSkippedEvent `json:"value"`
		}{"CompactionSkipped", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: AgentEvent has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown AgentEvent variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *AgentEvent) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "InputMessage":
		var v InputMessageEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventInputMessage{Value: v}
		return nil
	case "MessageStart":
		var v MessageStartEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventMessageStart{Value: v}
		return nil
	case "MessageStop":
		var v MessageStopEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventMessageStop{Value: v}
		return nil
	case "MessageComplete":
		var v MessageCompleteEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventMessageComplete{Value: v}
		return nil
	case "TextBlockStart":
		var v TextBlockStartEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventTextBlockStart{Value: v}
		return nil
	case "TextChunk":
		var v TextChunkEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventTextChunk{Value: v}
		return nil
	case "ThinkingBlockStart":
		var v ThinkingBlockStartEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventThinkingBlockStart{Value: v}
		return nil
	case "ThinkingChunk":
		var v ThinkingChunkEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventThinkingChunk{Value: v}
		return nil
	case "ThinkingSignatureChunk":
		var v ThinkingSignatureChunkEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventThinkingSignatureChunk{Value: v}
		return nil
	case "ToolCallStart":
		var v ToolCallStartEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventToolCallStart{Value: v}
		return nil
	case "ToolCallInputDelta":
		var v ToolCallInputDeltaEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventToolCallInputDelta{Value: v}
		return nil
	case "ContentBlockStop":
		var v ContentBlockStopEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventContentBlockStop{Value: v}
		return nil
	case "ToolExecuting":
		var v ToolExecutingEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventToolExecuting{Value: v}
		return nil
	case "ToolComplete":
		var v ToolCompleteEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventToolComplete{Value: v}
		return nil
	case "RunComplete":
		var v RunCompleteEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventRunComplete{Value: v}
		return nil
	case "RunAborted":
		var v RunAbortedEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventRunAborted{Value: v}
		return nil
	case "Compacted":
		var v CompactedEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventCompacted{Value: v}
		return nil
	case "CompactionSkipped":
		var v CompactionSkippedEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = AgentEventCompactionSkipped{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown AgentEvent variant tag %q", envelope.Type)
	}
}
