// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One key-value annotation on a session. Annotations ride as a vec of
// entries (fluorite has no map type); keys are unique per session.
type AnnotationEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}
