// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Answers to every question one agent is parked on, delivered together
type AnswerAsksRequest struct {
	Answers []AskAnswerInput `json:"answers"`
}
