// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The agent asked the user something and is parked on it.
type AskLifecycle struct {
	ToolCallID *string `json:"toolCallId,omitempty"`
	Question   string  `json:"question"`
}
