// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One thing a bundle offers, as the settings page lists it and the composer
// completes it.
//
// No template: the server expands an invocation from its own copy, so a client
// never needs a command's body — and some of them run past a page.
type CatalogEntryView struct {
	// `command`, `skill` or `agent`. Commands and skills are typed `/name`,
	// agents `@name`.
	Kind        string `json:"kind"`
	Name        string `json:"name"`
	Description string `json:"description"`
	// `argument-hint`, shown beside the name. Commands only.
	ArgumentHint *string `json:"argumentHint,omitempty"`
}
