// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// CompactionTriggerVariant is implemented by every variant of CompactionTrigger.
type CompactionTriggerVariant interface {
	isCompactionTriggerVariant()
}

type CompactionTriggerAuto struct {
	Value EmptyOutcome
}

func (CompactionTriggerAuto) isCompactionTriggerVariant() {}

type CompactionTriggerManual struct {
	Value EmptyOutcome
}

func (CompactionTriggerManual) isCompactionTriggerVariant() {}

// Why a compaction happened. Two arms rather than a bool so a third reason
// (a provider overflow, say) is an arm rather than a second flag.
// CompactionTrigger is an adjacently tagged union: its JSON carries the variant name
// in "kind" and any payload in "value".
type CompactionTrigger struct {
	Variant CompactionTriggerVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u CompactionTrigger) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case CompactionTriggerAuto:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Auto", v.Value})
	case CompactionTriggerManual:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Manual", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: CompactionTrigger has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown CompactionTrigger variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *CompactionTrigger) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"kind"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Auto":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = CompactionTriggerAuto{Value: v}
		return nil
	case "Manual":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = CompactionTriggerManual{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown CompactionTrigger variant tag %q", envelope.Type)
	}
}
