// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A compaction that was asked for and folded nothing. Carries the same
// account the journaled lifecycle entry does, because it becomes one.
type CompactionSkippedEvent struct {
	Detail CompactionSkippedLifecycle `json:"detail"`
	AtMs   uint64                     `json:"atMs"`
}
