// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The hook ran and may have injected context into the model.
type ContextInjected struct {
	AdditionalContext *string `json:"additionalContext,omitempty"`
}
