// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// ContentPartVariant is implemented by every variant of ContentPart.
type ContentPartVariant interface {
	isContentPartVariant()
}

type ContentPartText struct {
	Value TextPart
}

func (ContentPartText) isContentPartVariant() {}

type ContentPartToolCall struct {
	Value ToolCallPart
}

func (ContentPartToolCall) isContentPartVariant() {}

type ContentPartToolResult struct {
	Value ToolResultPart
}

func (ContentPartToolResult) isContentPartVariant() {}

type ContentPartThinking struct {
	Value ThinkingPart
}

func (ContentPartThinking) isContentPartVariant() {}

type ContentPartSubAgentResult struct {
	Value SubAgentResultPart
}

func (ContentPartSubAgentResult) isContentPartVariant() {}

// Content variant within a message
// ContentPart is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type ContentPart struct {
	Variant ContentPartVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u ContentPart) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case ContentPartText:
		return json.Marshal(struct {
			Type  string   `json:"type"`
			Value TextPart `json:"value"`
		}{"Text", v.Value})
	case ContentPartToolCall:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value ToolCallPart `json:"value"`
		}{"ToolCall", v.Value})
	case ContentPartToolResult:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value ToolResultPart `json:"value"`
		}{"ToolResult", v.Value})
	case ContentPartThinking:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value ThinkingPart `json:"value"`
		}{"Thinking", v.Value})
	case ContentPartSubAgentResult:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value SubAgentResultPart `json:"value"`
		}{"SubAgentResult", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: ContentPart has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown ContentPart variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *ContentPart) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Text":
		var v TextPart
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ContentPartText{Value: v}
		return nil
	case "ToolCall":
		var v ToolCallPart
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ContentPartToolCall{Value: v}
		return nil
	case "ToolResult":
		var v ToolResultPart
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ContentPartToolResult{Value: v}
		return nil
	case "Thinking":
		var v ThinkingPart
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ContentPartThinking{Value: v}
		return nil
	case "SubAgentResult":
		var v SubAgentResultPart
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ContentPartSubAgentResult{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown ContentPart variant tag %q", envelope.Type)
	}
}
