// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A session is created *with* the first thing to say to it. There is no
// create-then-message shape: a session with no message is a provisioned
// runtime nobody asked a question, and nothing reclaims one.
type CreateSessionRequest struct {
	Name  *string       `json:"name,omitempty"`
	Agent AgentSettings `json:"agent"`
	// The first user message, queued as part of the create. Required and
	// non-empty.
	Message string `json:"message"`
	// Runtime vendor name; defaults to "local".
	Vendor *string `json:"vendor,omitempty"`
	// Repositories cloned into a vendor-managed workspace at provision time.
	// Only honored by a vendor that supports provisioning; the UI sends these
	// only for such a vendor.
	Repos *[]RepoConfig `json:"repos,omitempty"`
	// Selected plugin-bundle names to provision for this session; absent →
	// the server's default-enabled bundles. Non-empty implies plugins are on.
	Plugins *[]string `json:"plugins,omitempty"`
}
