// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A session is created *with* the first thing to say to it. There is no
// create-then-message shape: a session with no message is a provisioned
// runtime nobody asked a question, and nothing reclaims one.
type CreateSessionRequest struct {
	Name  *string       `json:"name,omitempty"`
	Agent AgentSettings `json:"agent"`
	// The first user message, queued as part of the create. Required and
	// non-empty.
	Message string `json:"message"`
	// Where this session runs and what it runs against. Required — a session
	// that did not say has not chosen, it has been chosen for.
	Environment EnvironmentSpec `json:"environment"`
	// Selected plugin-bundle names to provision for this session; absent →
	// the server's default-enabled bundles. Non-empty implies plugins are on.
	Plugins *[]string `json:"plugins,omitempty"`
}
