// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Every day at `hour:minute` in `timezone`.
type DailySchedule struct {
	Timezone string `json:"timezone"`
	Hour     uint32 `json:"hour"`
	Minute   uint32 `json:"minute"`
}
