// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The owning session was deleted; the vendor decides the runtime's fate.
type DeleteRuntimeRequest struct {
	RuntimeID string `json:"runtimeId"`
}
