// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// What the CLI gets when it starts a device authorization. The device code is
// the secret it polls with; the user code is what a human reads out and types.
type DeviceCodeResponse struct {
	DeviceCode      string `json:"deviceCode"`
	UserCode        string `json:"userCode"`
	VerificationURI string `json:"verificationUri"`
	// The same page with the code pre-filled, for when the CLI can print a
	// link the user can click.
	VerificationURIComplete string `json:"verificationUriComplete"`
	// Seconds until the code expires.
	ExpiresIn uint32 `json:"expiresIn"`
	// Seconds the CLI must wait between polls while the code is still
	// pending. Polling faster is answered with `slow_down`.
	Interval uint32 `json:"interval"`
}
