// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Approve or deny a pending device authorization from the browser.
type DeviceApprovalRequest struct {
	UserCode string `json:"userCode"`
}
