// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A directory-subtree grant (`nono::allow_path`).
type DirGrant struct {
	Path   string `json:"path"`
	Access Access `json:"access"`
}
