// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One environment variable explicitly injected into a spawned runtime child
// (e.g. a capability token or a synthetic `HOME`).
type EnvVar struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}
