// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Create or fully replace an environment. Omitted list fields default to
// empty; `description` defaults to "".
type EnvironmentInput struct {
	Name        string           `json:"name"`
	Description *string          `json:"description,omitempty"`
	Vendor      string           `json:"vendor"`
	Repos       *[]RepoConfig    `json:"repos,omitempty"`
	EnvVars     *[]EnvVar        `json:"envVars,omitempty"`
	Provision   *[]ProvisionStep `json:"provision,omitempty"`
}
