// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A predefined environment as shown to clients.
type EnvironmentView struct {
	// Slug; the id of record, used in API paths.
	Name        string `json:"name"`
	Description string `json:"description"`
	// Runtime vendor name. Required, and never "local": environments only
	// target vendor-managed, provisionable runtimes.
	Vendor string `json:"vendor"`
	// Repositories cloned into the runtime workspace at provision time.
	Repos []RepoConfig `json:"repos"`
	// Plain-text, non-sensitive env vars for the runtime. Secrets are a
	// future, separate concept. Names in the server's reserved `HORSIE_*`
	// namespace are refused at save.
	EnvVars []EnvVar `json:"envVars"`
	// Setup steps the runtime executes before its message loop, after the
	// repo checkouts — a step like `make setup` needs its repo on disk.
	Provision []ProvisionStep `json:"provision"`
	// Unix epoch seconds.
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
