// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// EnvironmentSpecVariant is implemented by every variant of EnvironmentSpec.
type EnvironmentSpecVariant interface {
	isEnvironmentSpecVariant()
}

type EnvironmentSpecRuntime struct {
	Value RuntimeEnvironment
}

func (EnvironmentSpecRuntime) isEnvironmentSpecVariant() {}

type EnvironmentSpecNamed struct {
	Value NamedEnvironment
}

func (EnvironmentSpecNamed) isEnvironmentSpecVariant() {}

// Where a session runs and what it runs against. Required by every path that
// creates one: an optional environment would be a second, invisible way to
// answer the question, settled by a server default nobody asked for.
// EnvironmentSpec is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type EnvironmentSpec struct {
	Variant EnvironmentSpecVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u EnvironmentSpec) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case EnvironmentSpecRuntime:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value RuntimeEnvironment `json:"value"`
		}{"Runtime", v.Value})
	case EnvironmentSpecNamed:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value NamedEnvironment `json:"value"`
		}{"Named", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: EnvironmentSpec has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown EnvironmentSpec variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *EnvironmentSpec) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Runtime":
		var v RuntimeEnvironment
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = EnvironmentSpecRuntime{Value: v}
		return nil
	case "Named":
		var v NamedEnvironment
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = EnvironmentSpecNamed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown EnvironmentSpec variant tag %q", envelope.Type)
	}
}
