// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Triggered every `interval_secs` seconds. The next run is scheduled from
// when the previous one fired, not from a fixed origin, so a server that was
// down resumes with one run rather than a backlog. Minimum 60 seconds.
type EverySchedule struct {
	IntervalSecs uint64 `json:"intervalSecs"`
}
