// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A single-file grant, e.g. a device node (`nono::allow_file`).
type FileGrant struct {
	Path   string `json:"path"`
	Access Access `json:"access"`
}
