// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type FindAndReplaceInput struct {
	Path       string `json:"path"`
	Find       string `json:"find"`
	Replace    string `json:"replace"`
	Regex      *bool  `json:"regex,omitempty"`
	ReplaceAll *bool  `json:"replaceAll,omitempty"`
}
