// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// How a Fly Machines vendor builds machines.
type FlyVendorSettings struct {
	// The Fly app machines are created in. Must already exist — the server
	// creates machines, not apps.
	App string `json:"app"`
	// OCI image with `horsie-runtime` baked in.
	Image  string `json:"image"`
	Region string `json:"region"`
	// Where in the machine workspaces are allocated.
	WorkspaceRoot string `json:"workspaceRoot"`
	// The `ws://`/`wss://` URL a machine reaches this server on, including the
	// connect path — a URL with no path is refused rather than completed, so
	// what is stored is always what was sent. An address that only resolves on
	// the server's own loopback is refused too: a machine could never reach
	// it, and the failure would otherwise surface as an unexplained session
	// timeout.
	CallbackURL string `json:"callbackUrl"`
	// Give each runtime a volume, so a stopped one keeps its workspace.
	Volumes      bool   `json:"volumes"`
	CPUKind      string `json:"cpuKind"`
	Cpus         uint32 `json:"cpus"`
	MemoryMb     uint32 `json:"memoryMb"`
	VolumeSizeGb uint32 `json:"volumeSizeGb"`
}
