// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The GitHub App config, redacted for display. Secrets are reported only as
// `has_*` booleans.
type GitHubAppConfigView struct {
	ClientID string  `json:"clientId"`
	AppID    *uint64 `json:"appId,omitempty"`
	AppSlug  *string `json:"appSlug,omitempty"`
	// True when a client secret is stored.
	HasClientSecret bool `json:"hasClientSecret"`
	// True when a private key (PEM) is stored.
	HasPrivateKey bool `json:"hasPrivateKey"`
	// Public base URL for OAuth callbacks; NULL derives from the request host.
	CallbackBase *string `json:"callbackBase,omitempty"`
}
