// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One repository visible to the App installation.
type GitHubRepo struct {
	// "owner/name".
	FullName      string `json:"fullName"`
	Private       bool   `json:"private"`
	DefaultBranch string `json:"defaultBranch"`
}
