// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Current GitHub connection state, for the Settings UI.
type GitHubStatus struct {
	// True once an account is connected (OAuth credentials stored).
	Connected bool `json:"connected"`
	// Login of the connected account, when connected.
	Login *string `json:"login,omitempty"`
	// True once the GitHub App is configured (client id present).
	AppConfigured bool `json:"appConfigured"`
	// Repos visible to the installation; 0 until the first repo listing.
	RepoCount uint32 `json:"repoCount"`
}
