// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// GitHub App config to persist. Write-only secrets: omit to keep the stored
// value, "" to clear, a value to set.
type GitHubAppConfigInput struct {
	ClientID     string  `json:"clientId"`
	ClientSecret *string `json:"clientSecret,omitempty"`
	AppID        *uint64 `json:"appId,omitempty"`
	PrivateKey   *string `json:"privateKey,omitempty"`
	AppSlug      *string `json:"appSlug,omitempty"`
	CallbackBase *string `json:"callbackBase,omitempty"`
}
