// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// GlobalSessionEventVariant is implemented by every variant of GlobalSessionEvent.
type GlobalSessionEventVariant interface {
	isGlobalSessionEventVariant()
}

type GlobalSessionEventStatusChanged struct {
	Value GlobalSessionStatusEvent
}

func (GlobalSessionEventStatusChanged) isGlobalSessionEventVariant() {}

type GlobalSessionEventTitleChanged struct {
	Value GlobalSessionTitleEvent
}

func (GlobalSessionEventTitleChanged) isGlobalSessionEventVariant() {}

// One frame on the global `/api/events` stream (live session-list updates).
// GlobalSessionEvent is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type GlobalSessionEvent struct {
	Variant GlobalSessionEventVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u GlobalSessionEvent) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case GlobalSessionEventStatusChanged:
		return json.Marshal(struct {
			Type  string                   `json:"type"`
			Value GlobalSessionStatusEvent `json:"value"`
		}{"StatusChanged", v.Value})
	case GlobalSessionEventTitleChanged:
		return json.Marshal(struct {
			Type  string                  `json:"type"`
			Value GlobalSessionTitleEvent `json:"value"`
		}{"TitleChanged", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: GlobalSessionEvent has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown GlobalSessionEvent variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *GlobalSessionEvent) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "StatusChanged":
		var v GlobalSessionStatusEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = GlobalSessionEventStatusChanged{Value: v}
		return nil
	case "TitleChanged":
		var v GlobalSessionTitleEvent
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = GlobalSessionEventTitleChanged{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown GlobalSessionEvent variant tag %q", envelope.Type)
	}
}
