// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A status frame on the global `/api/events` stream.
type GlobalSessionStatusEvent struct {
	SessionID string            `json:"sessionId"`
	Status    SessionStatusKind `json:"status"`
	Reason    *string           `json:"reason,omitempty"`
}
