// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A title frame on the global `/api/events` stream.
type GlobalSessionTitleEvent struct {
	SessionID string `json:"sessionId"`
	Name      string `json:"name"`
}
