// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type GlobInput struct {
	Pattern    string  `json:"pattern"`
	Path       *string `json:"path,omitempty"`
	MaxResults *uint64 `json:"maxResults,omitempty"`
}
