// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// GrantVariant is implemented by every variant of Grant.
type GrantVariant interface {
	isGrantVariant()
}

type GrantDir struct {
	Value DirGrant
}

func (GrantDir) isGrantVariant() {}

type GrantFile struct {
	Value FileGrant
}

func (GrantFile) isGrantVariant() {}

type GrantWorkingDir struct {
	Value WorkingDirGrant
}

func (GrantWorkingDir) isGrantVariant() {}

// A single capability grant. The kind is explicit so directory-vs-file intent is
// unambiguous; `nono`'s `allow_path` is directory-only and `allow_file` single-file.
// Grant is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type Grant struct {
	Variant GrantVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u Grant) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case GrantDir:
		return json.Marshal(struct {
			Type  string   `json:"type"`
			Value DirGrant `json:"value"`
		}{"Dir", v.Value})
	case GrantFile:
		return json.Marshal(struct {
			Type  string    `json:"type"`
			Value FileGrant `json:"value"`
		}{"File", v.Value})
	case GrantWorkingDir:
		return json.Marshal(struct {
			Type  string          `json:"type"`
			Value WorkingDirGrant `json:"value"`
		}{"WorkingDir", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: Grant has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown Grant variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *Grant) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Dir":
		var v DirGrant
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = GrantDir{Value: v}
		return nil
	case "File":
		var v FileGrant
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = GrantFile{Value: v}
		return nil
	case "WorkingDir":
		var v WorkingDirGrant
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = GrantWorkingDir{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown Grant variant tag %q", envelope.Type)
	}
}
