// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type GrepInput struct {
	Pattern     string  `json:"pattern"`
	Path        *string `json:"path,omitempty"`
	FilePattern *string `json:"filePattern,omitempty"`
	MaxResults  *uint64 `json:"maxResults,omitempty"`
}
