// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Agent handed off control. A conclusion is always one call; a park (an
// optional handoff, e.g. `ask_user`) may be several issued in the same turn,
// and all of them are answered together
type HandoffOutput struct {
	ToolName string        `json:"toolName"`
	Calls    []HandoffCall `json:"calls"`
}
