// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// HistoryEntryVariant is implemented by every variant of HistoryEntry.
type HistoryEntryVariant interface {
	isHistoryEntryVariant()
}

type HistoryEntryLLM struct {
	Value Message
}

func (HistoryEntryLLM) isHistoryEntryVariant() {}

type HistoryEntryHook struct {
	Value HookEntry
}

func (HistoryEntryHook) isHistoryEntryVariant() {}

// One item in an agent's transcript.
//
// A transcript is not a conversation: a `Hook` entry is what a plugin *did*, and
// only some of those put text in front of the model. `AgentState::prompt_messages`
// translates every entry on the way to a provider, and most hook entries
// translate to nothing — a tool hook edited the tool's own output, so the tool
// result already carries it. Because the union sits above `Message` rather than
// inside `ContentPart`, no provider ever holds an arm for an entry it would have
// to interpret itself, and clients keep receiving hook entries verbatim so an
// intervention renders as an intervention rather than as something the user said.
// HistoryEntry is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type HistoryEntry struct {
	Variant HistoryEntryVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u HistoryEntry) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case HistoryEntryLLM:
		return json.Marshal(struct {
			Type  string  `json:"type"`
			Value Message `json:"value"`
		}{"Llm", v.Value})
	case HistoryEntryHook:
		return json.Marshal(struct {
			Type  string    `json:"type"`
			Value HookEntry `json:"value"`
		}{"Hook", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: HistoryEntry has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown HistoryEntry variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *HistoryEntry) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Llm":
		var v Message
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HistoryEntryLLM{Value: v}
		return nil
	case "Hook":
		var v HookEntry
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HistoryEntryHook{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown HistoryEntry variant tag %q", envelope.Type)
	}
}
