// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Every other event's refusal, via top-level `decision: "block"` or exit 2.
// For `Stop` this means *blocked from stopping*, which continues the turn.
type HookBlocked struct {
	Reason *string `json:"reason,omitempty"`
}
