// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The hook never ran to completion: spawn failure, timeout, or a non-zero exit
// that is not a refusal. An outage, never a decision.
type HookFailed struct {
	Reason string `json:"reason"`
}
