// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A value a hook replaced. Both halves or neither — never a dangling "before".
type HookRewrite struct {
	Before string `json:"before"`
	After  string `json:"after"`
}
