// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A `PreToolUse` refusal, via `permissionDecision: "deny"` or exit 2.
type HookDenied struct {
	Reason *string `json:"reason,omitempty"`
}
