// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// HookActionVariant is implemented by every variant of HookAction.
type HookActionVariant interface {
	isHookActionVariant()
}

type HookActionPreToolUse struct {
	Value PreToolUseRecord
}

func (HookActionPreToolUse) isHookActionVariant() {}

type HookActionPostToolUse struct {
	Value PostToolUseRecord
}

func (HookActionPostToolUse) isHookActionVariant() {}

type HookActionPostToolUseFailure struct {
	Value PostToolUseFailureRecord
}

func (HookActionPostToolUseFailure) isHookActionVariant() {}

type HookActionPostToolBatch struct {
	Value PostToolBatchRecord
}

func (HookActionPostToolBatch) isHookActionVariant() {}

type HookActionSessionStart struct {
	Value SessionStartRecord
}

func (HookActionSessionStart) isHookActionVariant() {}

type HookActionSessionEnd struct {
	Value SessionEndRecord
}

func (HookActionSessionEnd) isHookActionVariant() {}

type HookActionUserPromptSubmit struct {
	Value UserPromptSubmitRecord
}

func (HookActionUserPromptSubmit) isHookActionVariant() {}

type HookActionUserPromptExpansion struct {
	Value UserPromptExpansionRecord
}

func (HookActionUserPromptExpansion) isHookActionVariant() {}

type HookActionStop struct {
	Value StopRecord
}

func (HookActionStop) isHookActionVariant() {}

type HookActionStopFailure struct {
	Value StopFailureRecord
}

func (HookActionStopFailure) isHookActionVariant() {}

type HookActionSubagentStart struct {
	Value SubagentStartRecord
}

func (HookActionSubagentStart) isHookActionVariant() {}

type HookActionSubagentStop struct {
	Value SubagentStopRecord
}

func (HookActionSubagentStop) isHookActionVariant() {}

type HookActionTaskCreated struct {
	Value TaskCreatedRecord
}

func (HookActionTaskCreated) isHookActionVariant() {}

type HookActionTaskCompleted struct {
	Value TaskCompletedRecord
}

func (HookActionTaskCompleted) isHookActionVariant() {}

type HookActionNotification struct {
	Value NotificationRecord
}

func (HookActionNotification) isHookActionVariant() {}

type HookActionCwdChanged struct {
	Value CwdChangedRecord
}

func (HookActionCwdChanged) isHookActionVariant() {}

// What one hook did, tagged by the event it ran for.
//
// Named `HookAction` rather than `HookEvent` because
// `horsie_support::plugin::hooks::HookEvent` already exists as the name
// classifier that powers install-time refusal. Two jobs, two names.
// HookAction is an adjacently tagged union: its JSON carries the variant name
// in "event" and any payload in "value".
type HookAction struct {
	Variant HookActionVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u HookAction) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case HookActionPreToolUse:
		return json.Marshal(struct {
			Type  string           `json:"event"`
			Value PreToolUseRecord `json:"value"`
		}{"PreToolUse", v.Value})
	case HookActionPostToolUse:
		return json.Marshal(struct {
			Type  string            `json:"event"`
			Value PostToolUseRecord `json:"value"`
		}{"PostToolUse", v.Value})
	case HookActionPostToolUseFailure:
		return json.Marshal(struct {
			Type  string                   `json:"event"`
			Value PostToolUseFailureRecord `json:"value"`
		}{"PostToolUseFailure", v.Value})
	case HookActionPostToolBatch:
		return json.Marshal(struct {
			Type  string              `json:"event"`
			Value PostToolBatchRecord `json:"value"`
		}{"PostToolBatch", v.Value})
	case HookActionSessionStart:
		return json.Marshal(struct {
			Type  string             `json:"event"`
			Value SessionStartRecord `json:"value"`
		}{"SessionStart", v.Value})
	case HookActionSessionEnd:
		return json.Marshal(struct {
			Type  string           `json:"event"`
			Value SessionEndRecord `json:"value"`
		}{"SessionEnd", v.Value})
	case HookActionUserPromptSubmit:
		return json.Marshal(struct {
			Type  string                 `json:"event"`
			Value UserPromptSubmitRecord `json:"value"`
		}{"UserPromptSubmit", v.Value})
	case HookActionUserPromptExpansion:
		return json.Marshal(struct {
			Type  string                    `json:"event"`
			Value UserPromptExpansionRecord `json:"value"`
		}{"UserPromptExpansion", v.Value})
	case HookActionStop:
		return json.Marshal(struct {
			Type  string     `json:"event"`
			Value StopRecord `json:"value"`
		}{"Stop", v.Value})
	case HookActionStopFailure:
		return json.Marshal(struct {
			Type  string            `json:"event"`
			Value StopFailureRecord `json:"value"`
		}{"StopFailure", v.Value})
	case HookActionSubagentStart:
		return json.Marshal(struct {
			Type  string              `json:"event"`
			Value SubagentStartRecord `json:"value"`
		}{"SubagentStart", v.Value})
	case HookActionSubagentStop:
		return json.Marshal(struct {
			Type  string             `json:"event"`
			Value SubagentStopRecord `json:"value"`
		}{"SubagentStop", v.Value})
	case HookActionTaskCreated:
		return json.Marshal(struct {
			Type  string            `json:"event"`
			Value TaskCreatedRecord `json:"value"`
		}{"TaskCreated", v.Value})
	case HookActionTaskCompleted:
		return json.Marshal(struct {
			Type  string              `json:"event"`
			Value TaskCompletedRecord `json:"value"`
		}{"TaskCompleted", v.Value})
	case HookActionNotification:
		return json.Marshal(struct {
			Type  string             `json:"event"`
			Value NotificationRecord `json:"value"`
		}{"Notification", v.Value})
	case HookActionCwdChanged:
		return json.Marshal(struct {
			Type  string           `json:"event"`
			Value CwdChangedRecord `json:"value"`
		}{"CwdChanged", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: HookAction has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown HookAction variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *HookAction) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"event"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "PreToolUse":
		var v PreToolUseRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionPreToolUse{Value: v}
		return nil
	case "PostToolUse":
		var v PostToolUseRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionPostToolUse{Value: v}
		return nil
	case "PostToolUseFailure":
		var v PostToolUseFailureRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionPostToolUseFailure{Value: v}
		return nil
	case "PostToolBatch":
		var v PostToolBatchRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionPostToolBatch{Value: v}
		return nil
	case "SessionStart":
		var v SessionStartRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionSessionStart{Value: v}
		return nil
	case "SessionEnd":
		var v SessionEndRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionSessionEnd{Value: v}
		return nil
	case "UserPromptSubmit":
		var v UserPromptSubmitRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionUserPromptSubmit{Value: v}
		return nil
	case "UserPromptExpansion":
		var v UserPromptExpansionRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionUserPromptExpansion{Value: v}
		return nil
	case "Stop":
		var v StopRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionStop{Value: v}
		return nil
	case "StopFailure":
		var v StopFailureRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionStopFailure{Value: v}
		return nil
	case "SubagentStart":
		var v SubagentStartRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionSubagentStart{Value: v}
		return nil
	case "SubagentStop":
		var v SubagentStopRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionSubagentStop{Value: v}
		return nil
	case "TaskCreated":
		var v TaskCreatedRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionTaskCreated{Value: v}
		return nil
	case "TaskCompleted":
		var v TaskCompletedRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionTaskCompleted{Value: v}
		return nil
	case "Notification":
		var v NotificationRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionNotification{Value: v}
		return nil
	case "CwdChanged":
		var v CwdChangedRecord
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = HookActionCwdChanged{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown HookAction variant tag %q", envelope.Type)
	}
}
