// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Input received by the agent — one per run() invocation
type InputMessageEvent struct {
	MessageID string     `json:"messageId"`
	Input     AgentInput `json:"input"`
}
