// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// InstallOutcomeVariant is implemented by every variant of InstallOutcome.
type InstallOutcomeVariant interface {
	isInstallOutcomeVariant()
}

type InstallOutcomeInstalled struct {
	Value PluginView
}

func (InstallOutcomeInstalled) isInstallOutcomeVariant() {}

type InstallOutcomeMarketplace struct {
	Value MarketplaceView
}

func (InstallOutcomeMarketplace) isInstallOutcomeVariant() {}

// What a pasted URL turned out to be.
// InstallOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type InstallOutcome struct {
	Variant InstallOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u InstallOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case InstallOutcomeInstalled:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value PluginView `json:"value"`
		}{"Installed", v.Value})
	case InstallOutcomeMarketplace:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value MarketplaceView `json:"value"`
		}{"Marketplace", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: InstallOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown InstallOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *InstallOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Installed":
		var v PluginView
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = InstallOutcomeInstalled{Value: v}
		return nil
	case "Marketplace":
		var v MarketplaceView
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = InstallOutcomeMarketplace{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown InstallOutcome variant tag %q", envelope.Type)
	}
}
