// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// LifecycleEventVariant is implemented by every variant of LifecycleEvent.
type LifecycleEventVariant interface {
	isLifecycleEventVariant()
}

type LifecycleEventRuntime struct {
	Value RuntimeLifecycle
}

func (LifecycleEventRuntime) isLifecycleEventVariant() {}

type LifecycleEventPreparing struct {
	Value PreparingLifecycle
}

func (LifecycleEventPreparing) isLifecycleEventVariant() {}

type LifecycleEventMessageQueued struct {
	Value QueuedLifecycle
}

func (LifecycleEventMessageQueued) isLifecycleEventVariant() {}

type LifecycleEventTurnBegan struct {
	Value TurnBeganLifecycle
}

func (LifecycleEventTurnBegan) isLifecycleEventVariant() {}

type LifecycleEventTurnEnded struct {
	Value TurnEndedLifecycle
}

func (LifecycleEventTurnEnded) isLifecycleEventVariant() {}

type LifecycleEventAskRecorded struct {
	Value AskLifecycle
}

func (LifecycleEventAskRecorded) isLifecycleEventVariant() {}

type LifecycleEventSubAgent struct {
	Value SubAgentLifecycle
}

func (LifecycleEventSubAgent) isLifecycleEventVariant() {}

type LifecycleEventStep struct {
	Value StepLifecycle
}

func (LifecycleEventStep) isLifecycleEventVariant() {}

type LifecycleEventTaskList struct {
	Value TaskListLifecycle
}

func (LifecycleEventTaskList) isLifecycleEventVariant() {}

type LifecycleEventSessionFailed struct {
	Value SessionFailedLifecycle
}

func (LifecycleEventSessionFailed) isLifecycleEventVariant() {}

// Something that happened to the session, recorded in the log of the agent it
// concerns.
//
// The session actor still owns every one of these; it notifies the agent so
// there is one ordered record to read rather than a second stream to reconcile
// against this one. Flow is one-directional: session to agent, never back.
// LifecycleEvent is an adjacently tagged union: its JSON carries the variant name
// in "kind" and any payload in "value".
type LifecycleEvent struct {
	Variant LifecycleEventVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u LifecycleEvent) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case LifecycleEventRuntime:
		return json.Marshal(struct {
			Type  string           `json:"kind"`
			Value RuntimeLifecycle `json:"value"`
		}{"Runtime", v.Value})
	case LifecycleEventPreparing:
		return json.Marshal(struct {
			Type  string             `json:"kind"`
			Value PreparingLifecycle `json:"value"`
		}{"Preparing", v.Value})
	case LifecycleEventMessageQueued:
		return json.Marshal(struct {
			Type  string          `json:"kind"`
			Value QueuedLifecycle `json:"value"`
		}{"MessageQueued", v.Value})
	case LifecycleEventTurnBegan:
		return json.Marshal(struct {
			Type  string             `json:"kind"`
			Value TurnBeganLifecycle `json:"value"`
		}{"TurnBegan", v.Value})
	case LifecycleEventTurnEnded:
		return json.Marshal(struct {
			Type  string             `json:"kind"`
			Value TurnEndedLifecycle `json:"value"`
		}{"TurnEnded", v.Value})
	case LifecycleEventAskRecorded:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value AskLifecycle `json:"value"`
		}{"AskRecorded", v.Value})
	case LifecycleEventSubAgent:
		return json.Marshal(struct {
			Type  string            `json:"kind"`
			Value SubAgentLifecycle `json:"value"`
		}{"SubAgent", v.Value})
	case LifecycleEventStep:
		return json.Marshal(struct {
			Type  string        `json:"kind"`
			Value StepLifecycle `json:"value"`
		}{"Step", v.Value})
	case LifecycleEventTaskList:
		return json.Marshal(struct {
			Type  string            `json:"kind"`
			Value TaskListLifecycle `json:"value"`
		}{"TaskList", v.Value})
	case LifecycleEventSessionFailed:
		return json.Marshal(struct {
			Type  string                 `json:"kind"`
			Value SessionFailedLifecycle `json:"value"`
		}{"SessionFailed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: LifecycleEvent has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown LifecycleEvent variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *LifecycleEvent) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"kind"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Runtime":
		var v RuntimeLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventRuntime{Value: v}
		return nil
	case "Preparing":
		var v PreparingLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventPreparing{Value: v}
		return nil
	case "MessageQueued":
		var v QueuedLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventMessageQueued{Value: v}
		return nil
	case "TurnBegan":
		var v TurnBeganLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventTurnBegan{Value: v}
		return nil
	case "TurnEnded":
		var v TurnEndedLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventTurnEnded{Value: v}
		return nil
	case "AskRecorded":
		var v AskLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventAskRecorded{Value: v}
		return nil
	case "SubAgent":
		var v SubAgentLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventSubAgent{Value: v}
		return nil
	case "Step":
		var v StepLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventStep{Value: v}
		return nil
	case "TaskList":
		var v TaskListLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventTaskList{Value: v}
		return nil
	case "SessionFailed":
		var v SessionFailedLifecycle
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = LifecycleEventSessionFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown LifecycleEvent variant tag %q", envelope.Type)
	}
}
