// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A registered marketplace and the catalogue it last offered.
type MarketplaceView struct {
	// The index's declared name, else the repo basename. Primary key.
	Name        string  `json:"name"`
	SourceURL   string  `json:"sourceUrl"`
	SourceRef   *string `json:"sourceRef,omitempty"`
	PluginCount uint32  `json:"pluginCount"`
	// When the index was last read, epoch millis as a string.
	UpdatedAt string                  `json:"updatedAt"`
	Plugins   []MarketplacePluginView `json:"plugins"`
	// Entries the index declared that could not be parsed. Shown rather than
	// dropped: a catalogue that quietly lost three plugins is a bug report
	// nobody files.
	Skipped []string `json:"skipped"`
}
