// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One plugin a marketplace offers, as cached from its index.
type MarketplacePluginView struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Version     *string `json:"version,omitempty"`
	// True when a bundle installed from this entry is already in the library,
	// so the picker can say "installed" instead of offering it again.
	Installed bool `json:"installed"`
}
