// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Static bearer auth input. `token`: omit to keep the stored value, "" to
// clear, a value to replace.
type McpBearerInput struct {
	Token *string `json:"token,omitempty"`
}
