// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// McpAuthViewVariant is implemented by every variant of McpAuthView.
type McpAuthViewVariant interface {
	isMcpAuthViewVariant()
}

type McpAuthViewNone struct {
	Value McpNoAuth
}

func (McpAuthViewNone) isMcpAuthViewVariant() {}

type McpAuthViewBearer struct {
	Value McpBearerView
}

func (McpAuthViewBearer) isMcpAuthViewVariant() {}

type McpAuthViewOAuth struct {
	Value McpOAuthView
}

func (McpAuthViewOAuth) isMcpAuthViewVariant() {}

type McpAuthViewGithubApp struct {
	Value McpGithubAppAuth
}

func (McpAuthViewGithubApp) isMcpAuthViewVariant() {}

// Redacted auth view for a configured server.
// McpAuthView is an adjacently tagged union: its JSON carries the variant name
// in "kind" and any payload in "value".
type McpAuthView struct {
	Variant McpAuthViewVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u McpAuthView) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case McpAuthViewNone:
		return json.Marshal(struct {
			Type  string    `json:"kind"`
			Value McpNoAuth `json:"value"`
		}{"None", v.Value})
	case McpAuthViewBearer:
		return json.Marshal(struct {
			Type  string        `json:"kind"`
			Value McpBearerView `json:"value"`
		}{"Bearer", v.Value})
	case McpAuthViewOAuth:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value McpOAuthView `json:"value"`
		}{"OAuth", v.Value})
	case McpAuthViewGithubApp:
		return json.Marshal(struct {
			Type  string           `json:"kind"`
			Value McpGithubAppAuth `json:"value"`
		}{"GithubApp", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: McpAuthView has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown McpAuthView variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *McpAuthView) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"kind"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "None":
		var v McpNoAuth
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthViewNone{Value: v}
		return nil
	case "Bearer":
		var v McpBearerView
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthViewBearer{Value: v}
		return nil
	case "OAuth":
		var v McpOAuthView
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthViewOAuth{Value: v}
		return nil
	case "GithubApp":
		var v McpGithubAppAuth
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthViewGithubApp{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown McpAuthView variant tag %q", envelope.Type)
	}
}
