// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Redacted OAuth 2.1 auth view. `connected` = a stored access token exists;
// secrets are redacted to flags. `client_id` is safe to surface (public).
type McpOAuthView struct {
	Connected       bool    `json:"connected"`
	ClientID        *string `json:"clientId,omitempty"`
	HasClientSecret bool    `json:"hasClientSecret"`
}
