// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One configured remote MCP server, redacted for display.
type McpServerView struct {
	// Stable id and namespace prefix for its tools (`mcp__<name>__<tool>`).
	Name string `json:"name"`
	// Streamable-HTTP endpoint.
	URL string `json:"url"`
	// Whether the last connect/test succeeded and the server is usable.
	Enabled bool        `json:"enabled"`
	Auth    McpAuthView `json:"auth"`
	// Tools advertised at the last successful test, for the UI.
	ToolCount *uint32 `json:"toolCount,omitempty"`
	// Last connect/test error, for the UI.
	LastError *string `json:"lastError,omitempty"`
}
