// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Static bearer auth, redacted — the token is replaced by a stored flag.
type McpBearerView struct {
	HasToken bool `json:"hasToken"`
}
