// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type McpDiscoverResponse struct {
	CallID string          `json:"callId"`
	Tools  []PluginMcpTool `json:"tools"`
	// Servers that contributed no tools. Reported rather than dropped, so a
	// broken declaration is visible without being fatal.
	Failures []McpServerFailure `json:"failures"`
}
