// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// GitHub MCP over the existing GitHub App connection: the bearer is a user
// token minted from `GithubService` at use time, never stored on the row.
type McpGithubAppAuth struct {
}
