// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Upsert input for a server. Secrets follow omit=keep, ""=clear semantics.
type McpServerInput struct {
	Name string       `json:"name"`
	URL  string       `json:"url"`
	Auth McpAuthInput `json:"auth"`
}
