// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// McpServerFailureVariant is implemented by every variant of McpServerFailure.
type McpServerFailureVariant interface {
	isMcpServerFailureVariant()
}

type McpServerFailureUnreachable struct {
	Value McpServerUnreachable
}

func (McpServerFailureUnreachable) isMcpServerFailureVariant() {}

type McpServerFailureNeedsAuth struct {
	Value McpServerNeedsAuth
}

func (McpServerFailureNeedsAuth) isMcpServerFailureVariant() {}

// Why a declared server contributed no tools this pass. Typed rather than a
// string because the two cases call for different answers: one is a broken
// plugin to report, the other is a consent flow to offer.
// McpServerFailure is an adjacently tagged union: its JSON carries the variant name
// in "failure" and any payload in "value".
type McpServerFailure struct {
	Variant McpServerFailureVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u McpServerFailure) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case McpServerFailureUnreachable:
		return json.Marshal(struct {
			Type  string               `json:"failure"`
			Value McpServerUnreachable `json:"value"`
		}{"Unreachable", v.Value})
	case McpServerFailureNeedsAuth:
		return json.Marshal(struct {
			Type  string             `json:"failure"`
			Value McpServerNeedsAuth `json:"value"`
		}{"NeedsAuth", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: McpServerFailure has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown McpServerFailure variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *McpServerFailure) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"failure"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Unreachable":
		var v McpServerUnreachable
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpServerFailureUnreachable{Value: v}
		return nil
	case "NeedsAuth":
		var v McpServerNeedsAuth
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpServerFailureNeedsAuth{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown McpServerFailure variant tag %q", envelope.Type)
	}
}
