// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Call one tool on a plugin-declared MCP server. `tool` is the namespaced name
// from discovery; the runtime splits it back into server and tool.
type McpInvokeRequest struct {
	CallID    string `json:"callId"`
	Tool      string `json:"tool"`
	Arguments string `json:"arguments"`
}
