// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// McpAuthInputVariant is implemented by every variant of McpAuthInput.
type McpAuthInputVariant interface {
	isMcpAuthInputVariant()
}

type McpAuthInputNone struct {
	Value McpNoAuth
}

func (McpAuthInputNone) isMcpAuthInputVariant() {}

type McpAuthInputBearer struct {
	Value McpBearerInput
}

func (McpAuthInputBearer) isMcpAuthInputVariant() {}

type McpAuthInputOAuth struct {
	Value McpOAuthInput
}

func (McpAuthInputOAuth) isMcpAuthInputVariant() {}

type McpAuthInputGithubApp struct {
	Value McpGithubAppAuth
}

func (McpAuthInputGithubApp) isMcpAuthInputVariant() {}

// Auth input for an upsert.
// McpAuthInput is an adjacently tagged union: its JSON carries the variant name
// in "kind" and any payload in "value".
type McpAuthInput struct {
	Variant McpAuthInputVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u McpAuthInput) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case McpAuthInputNone:
		return json.Marshal(struct {
			Type  string    `json:"kind"`
			Value McpNoAuth `json:"value"`
		}{"None", v.Value})
	case McpAuthInputBearer:
		return json.Marshal(struct {
			Type  string         `json:"kind"`
			Value McpBearerInput `json:"value"`
		}{"Bearer", v.Value})
	case McpAuthInputOAuth:
		return json.Marshal(struct {
			Type  string        `json:"kind"`
			Value McpOAuthInput `json:"value"`
		}{"OAuth", v.Value})
	case McpAuthInputGithubApp:
		return json.Marshal(struct {
			Type  string           `json:"kind"`
			Value McpGithubAppAuth `json:"value"`
		}{"GithubApp", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: McpAuthInput has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown McpAuthInput variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *McpAuthInput) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"kind"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "None":
		var v McpNoAuth
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthInputNone{Value: v}
		return nil
	case "Bearer":
		var v McpBearerInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthInputBearer{Value: v}
		return nil
	case "OAuth":
		var v McpOAuthInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthInputOAuth{Value: v}
		return nil
	case "GithubApp":
		var v McpGithubAppAuth
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = McpAuthInputGithubApp{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown McpAuthInput variant tag %q", envelope.Type)
	}
}
