// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The authorize URL to redirect the browser to, returned by `connect` for an
// `oauth` server after discovery + (if needed) dynamic client registration.
type McpAuthorizeUrl struct {
	URL string `json:"url"`
}
