// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// How horsie authenticates to a remote MCP server. Informational mirror of the
// `McpAuthView`/`McpAuthInput` tags.
type McpAuthKind string

const (
	McpAuthKindNone      McpAuthKind = "None"
	McpAuthKindBearer    McpAuthKind = "Bearer"
	McpAuthKindOAuth     McpAuthKind = "OAuth"
	McpAuthKindGithubApp McpAuthKind = "GithubApp"
)
