// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// It answered `401`. `resource_metadata` is the RFC 9728 URL its
// `WWW-Authenticate` named, when it named one.
type McpServerNeedsAuth struct {
	Server           string  `json:"server"`
	ResourceMetadata *string `json:"resourceMetadata,omitempty"`
}
