// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// It could not be reached at all: no such binary, a refused connection, a
// declaration that would not parse.
type McpServerUnreachable struct {
	Server string `json:"server"`
	Reason string `json:"reason"`
}
