// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Create a memory space. `name` must be a slug: lowercase letters, digits,
// '.', '_' and '-', starting with a letter or digit.
type MemorySpaceCreateInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}
