// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One memory, body included. Addressed by the agent as `<space>/<name>`.
type MemoryView struct {
	ID    uint64 `json:"id"`
	Space string `json:"space"`
	Name  string `json:"name"`
	// One line, shown in the agent's prompt index.
	Description string `json:"description"`
	// Markdown body, loaded on demand.
	Content string `json:"content"`
	// Unix epoch seconds.
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
