// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type MemoryCreateInput struct {
	Space       string `json:"space"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Content     string `json:"content"`
}
