// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Omitted fields are left unchanged; supplied ones are replaced wholesale.
type MemoryUpdateInput struct {
	Description *string `json:"description,omitempty"`
	Content     *string `json:"content,omitempty"`
}
