// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Rename a space and/or change its description. Omitted fields are unchanged.
// Renaming carries the space's memories across.
type MemorySpaceUpdateInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}
