// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A memory space as shown in the web UI.
type MemorySpaceView struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	// How many memories the space holds.
	MemoryCount uint32 `json:"memoryCount"`
}
