// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A single message in the conversation
type Message struct {
	ID    string        `json:"id"`
	Role  Role          `json:"role"`
	Parts []ContentPart `json:"parts"`
	// Unix-epoch ms when the server finalized this message — turn start for a
	// user message, stream completion for an assistant message, tool
	// completion for a tool result.
	CreatedAtMs uint64 `json:"createdAtMs"`
	// Unix-epoch ms when the provider call that produced this message was
	// issued. Assistant messages only; absent elsewhere.
	StartedAtMs *uint64 `json:"startedAtMs,omitempty"`
}
