// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// MessageFrameVariant is implemented by every variant of MessageFrame.
type MessageFrameVariant interface {
	isMessageFrameVariant()
}

type MessageFrameWindow struct {
	Value MessageWindow
}

func (MessageFrameWindow) isMessageFrameVariant() {}

type MessageFrameEntry struct {
	Value AgentLogEntry
}

func (MessageFrameEntry) isMessageFrameVariant() {}

type MessageFrameDelta struct {
	Value MessageDelta
}

func (MessageFrameDelta) isMessageFrameVariant() {}

// One frame on `GET /sessions/:id/messages`.
//
// Two arms because there are two kinds of thing to carry, and they differ in
// exactly one respect that matters: an `Entry` is durable and replayable, a
// `Delta` is neither. A tagged union rather than "whichever field is present"
// so a client's match is exhaustive and a third arm cannot be added silently.
// MessageFrame is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type MessageFrame struct {
	Variant MessageFrameVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u MessageFrame) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case MessageFrameWindow:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value MessageWindow `json:"value"`
		}{"Window", v.Value})
	case MessageFrameEntry:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value AgentLogEntry `json:"value"`
		}{"Entry", v.Value})
	case MessageFrameDelta:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value MessageDelta `json:"value"`
		}{"Delta", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: MessageFrame has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown MessageFrame variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *MessageFrame) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Window":
		var v MessageWindow
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = MessageFrameWindow{Value: v}
		return nil
	case "Entry":
		var v AgentLogEntry
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = MessageFrameEntry{Value: v}
		return nil
	case "Delta":
		var v MessageDelta
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = MessageFrameDelta{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown MessageFrame variant tag %q", envelope.Type)
	}
}
