// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A stored model card.
type ModelCard struct {
	// Official provider model id — the card's identity (e.g. "claude-sonnet-4-6").
	ModelID string `json:"modelId"`
	// Display label (e.g. "Claude Sonnet 4.6").
	Name string `json:"name"`
	// Total context window in tokens.
	ContextWindow *uint32 `json:"contextWindow,omitempty"`
	// Generation cap in tokens.
	MaxTokens *uint32 `json:"maxTokens,omitempty"`
	// Canonical thinking-effort values this model supports, ascending.
	ThinkingEfforts *[]string `json:"thinkingEfforts,omitempty"`
	// The provider's default effort, when documented.
	DefaultThinkingEffort *string `json:"defaultThinkingEffort,omitempty"`
	// Wire encoding for this model's thinking control.
	ThinkingDialect *string `json:"thinkingDialect,omitempty"`
	// Where this model is officially served (e.g. "https://api.deepseek.com").
	// Reference data only — nothing reads it, and an operator's configured
	// provider base URL always wins.
	BaseURL *string `json:"baseUrl,omitempty"`
	// This backend rejects a pinned `tool_choice` while thinking is enabled,
	// so thinking is disabled for those requests. Absent means false.
	ForcedToolsDisableThinking *bool  `json:"forcedToolsDisableThinking,omitempty"`
	CreatedAt                  string `json:"createdAt"`
	UpdatedAt                  string `json:"updatedAt"`
}
