// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A model alias to persist.
type ModelInput struct {
	Alias           string    `json:"alias"`
	Provider        string    `json:"provider"`
	ModelID         string    `json:"modelId"`
	MaxTokens       *uint32   `json:"maxTokens,omitempty"`
	ContextWindow   *uint32   `json:"contextWindow,omitempty"`
	ThinkingEfforts *[]string `json:"thinkingEfforts,omitempty"`
	ThinkingEffort  *string   `json:"thinkingEffort,omitempty"`
	ThinkingDialect *string   `json:"thinkingDialect,omitempty"`
	// This backend rejects a pinned `tool_choice` while thinking is enabled,
	// so thinking is disabled for those requests. Absent means false.
	ForcedToolsDisableThinking *bool `json:"forcedToolsDisableThinking,omitempty"`
}
