// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Create input for a model card.
type ModelCardInput struct {
	ModelID       string  `json:"modelId"`
	Name          string  `json:"name"`
	ContextWindow *uint32 `json:"contextWindow,omitempty"`
	MaxTokens     *uint32 `json:"maxTokens,omitempty"`
	// Canonical thinking-effort values this model supports, ascending.
	ThinkingEfforts *[]string `json:"thinkingEfforts,omitempty"`
	// The provider's default effort, when documented.
	DefaultThinkingEffort *string `json:"defaultThinkingEffort,omitempty"`
	// Wire encoding for this model's thinking control.
	ThinkingDialect *string `json:"thinkingDialect,omitempty"`
	// Where this model is officially served (e.g. "https://api.deepseek.com").
	BaseURL *string `json:"baseUrl,omitempty"`
	// This backend rejects a pinned `tool_choice` while thinking is enabled.
	// Absent means false.
	ForcedToolsDisableThinking *bool `json:"forcedToolsDisableThinking,omitempty"`
}
