// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One configured model alias.
type ModelView struct {
	// The alias sessions select (e.g. "sonnet").
	Alias string `json:"alias"`
	// Name of the provider this model routes to.
	Provider string `json:"provider"`
	// The provider's model identifier (e.g. "claude-sonnet-4-6").
	ModelID   string  `json:"modelId"`
	MaxTokens *uint32 `json:"maxTokens,omitempty"`
	// The model's total context window, in tokens. A built-in default is
	// applied for known model ids when a model is added with this omitted.
	ContextWindow *uint32 `json:"contextWindow,omitempty"`
	// Canonical thinking-effort values this model offers, in ascending order.
	// Absent → the model exposes no thinking control.
	ThinkingEfforts *[]string `json:"thinkingEfforts,omitempty"`
	// Default applied when a session does not choose one.
	ThinkingEffort *string `json:"thinkingEffort,omitempty"`
	// This backend rejects a pinned `tool_choice` while thinking is enabled,
	// so thinking is disabled for those requests. Absent means false.
	ForcedToolsDisableThinking *bool `json:"forcedToolsDisableThinking,omitempty"`
	// Wire encoding for this model's thinking control.
	ThinkingDialect *string `json:"thinkingDialect,omitempty"`
}
