// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// On `day_of_month` of every month in `timezone`. Months without that day
// (the 31st, the 29th–31st in February) are skipped entirely.
type MonthlySchedule struct {
	Timezone   string `json:"timezone"`
	Hour       uint32 `json:"hour"`
	Minute     uint32 `json:"minute"`
	DayOfMonth uint32 `json:"dayOfMonth"`
}
