// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A predefined environment, by name. Resolved and snapshotted when the session
// is created, so editing or deleting it never re-points one that exists.
type NamedEnvironment struct {
	Name string `json:"name"`
}
