// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// NetworkPolicyVariant is implemented by every variant of NetworkPolicy.
type NetworkPolicyVariant interface {
	isNetworkPolicyVariant()
}

type NetworkPolicyBlock struct {
	Value BlockNetwork
}

func (NetworkPolicyBlock) isNetworkPolicyVariant() {}

type NetworkPolicyAllow struct {
	Value AllowNetwork
}

func (NetworkPolicyAllow) isNetworkPolicyVariant() {}

type NetworkPolicyProxyOnly struct {
	Value ProxyOnlyNetwork
}

func (NetworkPolicyProxyOnly) isNetworkPolicyVariant() {}

// What network egress the sandbox permits. `Block` is the safe default.
// NetworkPolicy is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type NetworkPolicy struct {
	Variant NetworkPolicyVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u NetworkPolicy) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case NetworkPolicyBlock:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value BlockNetwork `json:"value"`
		}{"Block", v.Value})
	case NetworkPolicyAllow:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value AllowNetwork `json:"value"`
		}{"Allow", v.Value})
	case NetworkPolicyProxyOnly:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value ProxyOnlyNetwork `json:"value"`
		}{"ProxyOnly", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: NetworkPolicy has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown NetworkPolicy variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *NetworkPolicy) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Block":
		var v BlockNetwork
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = NetworkPolicyBlock{Value: v}
		return nil
	case "Allow":
		var v AllowNetwork
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = NetworkPolicyAllow{Value: v}
		return nil
	case "ProxyOnly":
		var v ProxyOnlyNetwork
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = NetworkPolicyProxyOnly{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown NetworkPolicy variant tag %q", envelope.Type)
	}
}
