// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Triggered once at `at_ms` (unix epoch millis) and never re-armed. An
// instant already in the past never fires; move it forward to re-arm.
type OnceSchedule struct {
	AtMs uint64 `json:"atMs"`
}
