// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// OutcomeFilterVariant is implemented by every variant of OutcomeFilter.
type OutcomeFilterVariant interface {
	isOutcomeFilterVariant()
}

type OutcomeFilterIn struct {
	Value OutcomeIn
}

func (OutcomeFilterIn) isOutcomeFilterVariant() {}

type OutcomeFilterNotIn struct {
	Value OutcomeNotIn
}

func (OutcomeFilterNotIn) isOutcomeFilterVariant() {}

// Which outcomes an edge is taken for.
//
// Two operators, not four: equality is a one-element `in`, and inequality a
// one-element `not_in`. Every value must be one the producing step declares,
// which is checked when the workflow is saved — so a mistyped outcome is a
// rejected form rather than a run that ends halfway.
// OutcomeFilter is an adjacently tagged union: its JSON carries the variant name
// in "op" and any payload in "value".
type OutcomeFilter struct {
	Variant OutcomeFilterVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u OutcomeFilter) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case OutcomeFilterIn:
		return json.Marshal(struct {
			Type  string    `json:"op"`
			Value OutcomeIn `json:"value"`
		}{"In", v.Value})
	case OutcomeFilterNotIn:
		return json.Marshal(struct {
			Type  string       `json:"op"`
			Value OutcomeNotIn `json:"value"`
		}{"NotIn", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: OutcomeFilter has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown OutcomeFilter variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *OutcomeFilter) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"op"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "In":
		var v OutcomeIn
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = OutcomeFilterIn{Value: v}
		return nil
	case "NotIn":
		var v OutcomeNotIn
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = OutcomeFilterNotIn{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown OutcomeFilter variant tag %q", envelope.Type)
	}
}
