// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A library entry as shown in the web UI (metadata only — never the bytes).
type PluginView struct {
	// Canonical bundle name (from plugin.json, else the marketplace entry's
	// name, else the repo basename).
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// Resolved version (manifest version, else the cloned commit sha).
	Version   *string `json:"version,omitempty"`
	SourceURL string  `json:"sourceUrl"`
	SourceRef *string `json:"sourceRef,omitempty"`
	// Everything the bundle offers, sorted by kind then name.
	Catalog []CatalogEntryView `json:"catalog"`
	// Whether the bundle ships hooks horsie will run.
	HasHooks bool `json:"hasHooks"`
	// Pre-checked in the new-session bundle picker.
	EnabledDefault bool   `json:"enabledDefault"`
	ArtifactSize   uint64 `json:"artifactSize"`
	// The marketplace this bundle came from, when it came from one. A bundle
	// installed from a plain git URL has none.
	Marketplace *string `json:"marketplace,omitempty"`
}
