// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Install a bundle, or register the catalogue a URL turned out to be.
//
// Exactly one of `source_url` and the `(marketplace, plugin_name)` pair must be
// given; the other two fields are then absent. Four optional fields rather than
// a union is a deliberate trade: this is an existing wire type, and a union
// would buy compile-time safety over one runtime check at the cost of
// reshaping every call site.
type PluginInstallInput struct {
	SourceURL   *string `json:"sourceUrl,omitempty"`
	SourceRef   *string `json:"sourceRef,omitempty"`
	Marketplace *string `json:"marketplace,omitempty"`
	PluginName  *string `json:"pluginName,omitempty"`
}
