// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Toggle whether a bundle is pre-selected for new sessions.
type PluginDefaultInput struct {
	EnabledDefault bool `json:"enabledDefault"`
}
