// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One tool a plugin-declared MCP server offers. `name` is already namespaced
// `mcp__<server>__<tool>`, the spelling admin-configured servers use — so
// `allowed_tools` and hook matchers see one vocabulary whichever path a tool
// came from.
type PluginMcpTool struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	// JSON Schema, verbatim from the server.
	InputSchema string `json:"inputSchema"`
}
