// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `trigger` is the matcher domain: auto | manual. Nothing can be decided
// afterwards, so this reports only whether the hook ran.
type PostCompactRecord struct {
	Trigger string            `json:"trigger"`
	Outcome SideEffectOutcome `json:"outcome"`
}
