// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// PostToolUseFailureOutcomeVariant is implemented by every variant of PostToolUseFailureOutcome.
type PostToolUseFailureOutcomeVariant interface {
	isPostToolUseFailureOutcomeVariant()
}

type PostToolUseFailureOutcomeRan struct {
	Value ContextInjected
}

func (PostToolUseFailureOutcomeRan) isPostToolUseFailureOutcomeVariant() {}

type PostToolUseFailureOutcomeBlocked struct {
	Value HookBlocked
}

func (PostToolUseFailureOutcomeBlocked) isPostToolUseFailureOutcomeVariant() {}

type PostToolUseFailureOutcomeFailed struct {
	Value HookFailed
}

func (PostToolUseFailureOutcomeFailed) isPostToolUseFailureOutcomeVariant() {}

// PostToolUseFailureOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type PostToolUseFailureOutcome struct {
	Variant PostToolUseFailureOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u PostToolUseFailureOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case PostToolUseFailureOutcomeRan:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value ContextInjected `json:"value"`
		}{"Ran", v.Value})
	case PostToolUseFailureOutcomeBlocked:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"Blocked", v.Value})
	case PostToolUseFailureOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: PostToolUseFailureOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown PostToolUseFailureOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *PostToolUseFailureOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v ContextInjected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PostToolUseFailureOutcomeRan{Value: v}
		return nil
	case "Blocked":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PostToolUseFailureOutcomeBlocked{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PostToolUseFailureOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown PostToolUseFailureOutcome variant tag %q", envelope.Type)
	}
}
