// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A compaction that happened. Same matcher domain as `PreCompact`; the token
// counts are what it bought.
type PostCompactInput struct {
	Trigger      string `json:"trigger"`
	TokensBefore uint32 `json:"tokensBefore"`
	TokensAfter  uint32 `json:"tokensAfter"`
}
