// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type PostToolUseRecord struct {
	Call          ToolScope          `json:"call"`
	SystemMessage *string            `json:"systemMessage,omitempty"`
	Outcome       PostToolUseOutcome `json:"outcome"`
}
