// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// PostToolUseOutcomeVariant is implemented by every variant of PostToolUseOutcome.
type PostToolUseOutcomeVariant interface {
	isPostToolUseOutcomeVariant()
}

type PostToolUseOutcomeRan struct {
	Value PostToolUseRan
}

func (PostToolUseOutcomeRan) isPostToolUseOutcomeVariant() {}

type PostToolUseOutcomeBlocked struct {
	Value HookBlocked
}

func (PostToolUseOutcomeBlocked) isPostToolUseOutcomeVariant() {}

type PostToolUseOutcomeFailed struct {
	Value HookFailed
}

func (PostToolUseOutcomeFailed) isPostToolUseOutcomeVariant() {}

// PostToolUseOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type PostToolUseOutcome struct {
	Variant PostToolUseOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u PostToolUseOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case PostToolUseOutcomeRan:
		return json.Marshal(struct {
			Type  string         `json:"outcome"`
			Value PostToolUseRan `json:"value"`
		}{"Ran", v.Value})
	case PostToolUseOutcomeBlocked:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"Blocked", v.Value})
	case PostToolUseOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: PostToolUseOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown PostToolUseOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *PostToolUseOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v PostToolUseRan
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PostToolUseOutcomeRan{Value: v}
		return nil
	case "Blocked":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PostToolUseOutcomeBlocked{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PostToolUseOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown PostToolUseOutcome variant tag %q", envelope.Type)
	}
}
