// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type PostToolUseRan struct {
	Output            *HookRewrite `json:"output,omitempty"`
	AdditionalContext *string      `json:"additionalContext,omitempty"`
}
