// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type PostToolUseFailureRecord struct {
	Call          ToolScope                 `json:"call"`
	SystemMessage *string                   `json:"systemMessage,omitempty"`
	Outcome       PostToolUseFailureOutcome `json:"outcome"`
}
