// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A whole batch of parallel calls, so it names every call rather than one.
type PostToolBatchRecord struct {
	Calls         []ToolScope          `json:"calls"`
	SystemMessage *string              `json:"systemMessage,omitempty"`
	Outcome       PostToolBatchOutcome `json:"outcome"`
}
