// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `trigger` is the matcher domain: auto | manual.
type PreCompactRecord struct {
	Trigger       string      `json:"trigger"`
	SystemMessage *string     `json:"systemMessage,omitempty"`
	Outcome       StopOutcome `json:"outcome"`
}
