// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type PreToolUseRecord struct {
	Call          ToolScope         `json:"call"`
	SystemMessage *string           `json:"systemMessage,omitempty"`
	Outcome       PreToolUseOutcome `json:"outcome"`
}
