// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `PreToolUse` allowed the call, having possibly rewritten its input. Only an
// allowed call can be rewritten, which is why the rewrite lives here.
type PreToolUseAllowed struct {
	Input *HookRewrite `json:"input,omitempty"`
}
