// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// PreToolUseOutcomeVariant is implemented by every variant of PreToolUseOutcome.
type PreToolUseOutcomeVariant interface {
	isPreToolUseOutcomeVariant()
}

type PreToolUseOutcomeAllowed struct {
	Value PreToolUseAllowed
}

func (PreToolUseOutcomeAllowed) isPreToolUseOutcomeVariant() {}

type PreToolUseOutcomeDenied struct {
	Value HookDenied
}

func (PreToolUseOutcomeDenied) isPreToolUseOutcomeVariant() {}

type PreToolUseOutcomeAsk struct{}

func (PreToolUseOutcomeAsk) isPreToolUseOutcomeVariant() {}

type PreToolUseOutcomeDefer struct{}

func (PreToolUseOutcomeDefer) isPreToolUseOutcomeVariant() {}

type PreToolUseOutcomeFailed struct {
	Value HookFailed
}

func (PreToolUseOutcomeFailed) isPreToolUseOutcomeVariant() {}

// The only event that can refuse a call before it runs, and the only one that
// can rewrite its input. No `additionalContext`: the spec does not offer it
// here, and there is no result yet to attach it to.
// PreToolUseOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type PreToolUseOutcome struct {
	Variant PreToolUseOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u PreToolUseOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case PreToolUseOutcomeAllowed:
		return json.Marshal(struct {
			Type  string            `json:"outcome"`
			Value PreToolUseAllowed `json:"value"`
		}{"Allowed", v.Value})
	case PreToolUseOutcomeDenied:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookDenied `json:"value"`
		}{"Denied", v.Value})
	case PreToolUseOutcomeAsk:
		return json.Marshal(struct {
			Type string `json:"outcome"`
		}{"Ask"})
	case PreToolUseOutcomeDefer:
		return json.Marshal(struct {
			Type string `json:"outcome"`
		}{"Defer"})
	case PreToolUseOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: PreToolUseOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown PreToolUseOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *PreToolUseOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Allowed":
		var v PreToolUseAllowed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PreToolUseOutcomeAllowed{Value: v}
		return nil
	case "Denied":
		var v HookDenied
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PreToolUseOutcomeDenied{Value: v}
		return nil
	case "Ask":
		u.Variant = PreToolUseOutcomeAsk{}
		return nil
	case "Defer":
		u.Variant = PreToolUseOutcomeDefer{}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = PreToolUseOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown PreToolUseOutcome variant tag %q", envelope.Type)
	}
}
