// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// How far this turn's setup has got: `scanning_workspace`, `connecting_tools`,
// `ready`. Narration, and free-form on purpose — nothing acts on it, and the
// stages differ per vendor.
type PreparingLifecycle struct {
	Stage  string  `json:"stage"`
	Detail *string `json:"detail,omitempty"`
}
