// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A resource-preparation progression — shown live while a turn spins up and
// kept for audit. `stage` is a stable key (`acquiring_runtime`,
// `scanning_workspace`, `connecting_tools`, `ready`); `detail` is optional
// human text; `at_ms` is the unix-epoch millisecond it occurred.
type ProgressionEvent struct {
	Stage  string  `json:"stage"`
	Detail *string `json:"detail,omitempty"`
	AtMs   uint64  `json:"atMs"`
}
