// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A provider to persist. Replaces any provider of the same `name`.
type ProviderInput struct {
	Name string `json:"name"`
	// Provider kind: "anthropic" or "openai".
	Kind    string  `json:"kind"`
	BaseURL *string `json:"baseUrl,omitempty"`
	// New inline key. Omit to keep the existing stored key; "" to clear.
	APIKey *string `json:"apiKey,omitempty"`
	// Retain thinking-block signatures from this provider. Omit for the
	// default (off) — required for genuine Anthropic, which validates them.
	KeepThinkingSignature *bool `json:"keepThinkingSignature,omitempty"`
}
