// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One configured LLM provider, redacted for display.
type ProviderView struct {
	// Provider name — the key a model's `provider` references.
	Name string `json:"name"`
	// Provider kind: "anthropic" or "openai".
	Kind    string  `json:"kind"`
	BaseURL *string `json:"baseUrl,omitempty"`
	// Whether this provider can authenticate at all: a ChatGPT plan is signed
	// in, any other kind has a stored `api_key`. Which of the two applies
	// follows from `kind`, so one flag serves both — and a provider that
	// cannot authenticate is one no model should be added to.
	HasCredential bool `json:"hasCredential"`
	// Retain thinking-block signatures from this provider. Required for
	// genuine Anthropic (it validates them on replay); off for
	// Anthropic-compatible endpoints, which do not.
	KeepThinkingSignature bool `json:"keepThinkingSignature"`
}
