// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A setup step the runtime executes inside its sandbox after credential
// provisioning and before the agent message loop (e.g. cloning a repository).
// `uses` selects the step kind — "git_checkout" is the only kind today; the
// runtime fails on unknown kinds (fail-closed, forward-compatible).
type ProvisionStep struct {
	// Display label, e.g. "checkout horsie".
	Name string `json:"name"`
	// Step kind: "git_checkout".
	Uses string `json:"uses"`
	// Open key/value params, interpreted per `uses`.
	With []StepParam `json:"with"`
}
