// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A message accepted into this agent's inbox and not yet carried into a turn.
type QueuedLifecycle struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}
