// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ReadFileInput struct {
	Path      string  `json:"path"`
	StartLine *uint64 `json:"startLine,omitempty"`
	EndLine   *uint64 `json:"endLine,omitempty"`
}
