// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Rename a session. Single line, non-empty, at most 60 characters — the same
// rule the agent's own title tool is held to.
type RenameSessionRequest struct {
	Name string `json:"name"`
}
