// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ReplaceLinesInput struct {
	Path        string `json:"path"`
	StartLine   uint64 `json:"startLine"`
	EndLine     uint64 `json:"endLine"`
	Replacement string `json:"replacement"`
}
