// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One repository to provision into the session workspace.
type RepoConfig struct {
	// HTTPS clone URL, e.g. "https://github.com/org/repo".
	URL string `json:"url"`
	// Branch, tag, or commit to check out; absent → default branch.
	GitRef *string `json:"gitRef,omitempty"`
	// Directory under the workspace; absent → repo basename (deduped).
	Dir *string `json:"dir,omitempty"`
}
