// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The failure reply to any request. Carries no runtime id — the `request_id`
// on the envelope already identifies what failed.
type RequestFailed struct {
	Message string `json:"message"`
}
