// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Role of the message sender
type Role string

const (
	RoleUser      Role = "User"
	RoleAssistant Role = "Assistant"
	RoleTool      Role = "Tool"
)
