// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// RoutineScheduleVariant is implemented by every variant of RoutineSchedule.
type RoutineScheduleVariant interface {
	isRoutineScheduleVariant()
}

type RoutineScheduleManual struct {
	Value ManualSchedule
}

func (RoutineScheduleManual) isRoutineScheduleVariant() {}

type RoutineScheduleEvery struct {
	Value EverySchedule
}

func (RoutineScheduleEvery) isRoutineScheduleVariant() {}

type RoutineScheduleOnce struct {
	Value OnceSchedule
}

func (RoutineScheduleOnce) isRoutineScheduleVariant() {}

type RoutineScheduleDaily struct {
	Value DailySchedule
}

func (RoutineScheduleDaily) isRoutineScheduleVariant() {}

type RoutineScheduleWeekly struct {
	Value WeeklySchedule
}

func (RoutineScheduleWeekly) isRoutineScheduleVariant() {}

type RoutineScheduleMonthly struct {
	Value MonthlySchedule
}

func (RoutineScheduleMonthly) isRoutineScheduleVariant() {}

type RoutineScheduleYearly struct {
	Value YearlySchedule
}

func (RoutineScheduleYearly) isRoutineScheduleVariant() {}

// When a routine fires by itself. A union rather than a kind + optional
// fields, so "every, with no interval" cannot be expressed.
// RoutineSchedule is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type RoutineSchedule struct {
	Variant RoutineScheduleVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u RoutineSchedule) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case RoutineScheduleManual:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value ManualSchedule `json:"value"`
		}{"Manual", v.Value})
	case RoutineScheduleEvery:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value EverySchedule `json:"value"`
		}{"Every", v.Value})
	case RoutineScheduleOnce:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value OnceSchedule `json:"value"`
		}{"Once", v.Value})
	case RoutineScheduleDaily:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value DailySchedule `json:"value"`
		}{"Daily", v.Value})
	case RoutineScheduleWeekly:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value WeeklySchedule `json:"value"`
		}{"Weekly", v.Value})
	case RoutineScheduleMonthly:
		return json.Marshal(struct {
			Type  string          `json:"type"`
			Value MonthlySchedule `json:"value"`
		}{"Monthly", v.Value})
	case RoutineScheduleYearly:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value YearlySchedule `json:"value"`
		}{"Yearly", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: RoutineSchedule has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown RoutineSchedule variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *RoutineSchedule) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Manual":
		var v ManualSchedule
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RoutineScheduleManual{Value: v}
		return nil
	case "Every":
		var v EverySchedule
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RoutineScheduleEvery{Value: v}
		return nil
	case "Once":
		var v OnceSchedule
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RoutineScheduleOnce{Value: v}
		return nil
	case "Daily":
		var v DailySchedule
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RoutineScheduleDaily{Value: v}
		return nil
	case "Weekly":
		var v WeeklySchedule
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RoutineScheduleWeekly{Value: v}
		return nil
	case "Monthly":
		var v MonthlySchedule
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RoutineScheduleMonthly{Value: v}
		return nil
	case "Yearly":
		var v YearlySchedule
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RoutineScheduleYearly{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown RoutineSchedule variant tag %q", envelope.Type)
	}
}
