// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A routine as shown to clients: its definition, plus what the schedule and
// the last trigger did.
type RoutineView struct {
	// Slug; the id of record, used in API paths.
	Name        string `json:"name"`
	Description string `json:"description"`
	// Name of the agent preset every run is configured from.
	Agent string `json:"agent"`
	// The message queued as each run's first user message.
	Prompt   string          `json:"prompt"`
	Schedule RoutineSchedule `json:"schedule"`
	// False pauses the timer. The run endpoint and the UI button still work.
	Enabled bool `json:"enabled"`
	// When the timer fires next; absent when nothing is scheduled (a manual
	// routine, a paused one, or a spent `Once`).
	NextRunAtMs *uint64 `json:"nextRunAtMs,omitempty"`
	// When a trigger was last attempted.
	LastRunAtMs *uint64 `json:"lastRunAtMs,omitempty"`
	// The session the last successful trigger created.
	LastSessionID *string `json:"lastSessionId,omitempty"`
	// Why the last trigger failed to create a session. A run that started and
	// then failed reports through its session, not here.
	LastError *string `json:"lastError,omitempty"`
	// Unix epoch seconds.
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
