// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The session a trigger created. It is running in the background by the time
// this is returned.
type RoutineRunResponse struct {
	Session SessionSummary `json:"session"`
}
