// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Create or fully replace a routine. `description` defaults to "", `schedule`
// to Manual, and `enabled` to true.
type RoutineInput struct {
	Name        string           `json:"name"`
	Description *string          `json:"description,omitempty"`
	Agent       string           `json:"agent"`
	Environment EnvironmentSpec  `json:"environment"`
	Prompt      string           `json:"prompt"`
	Schedule    *RoutineSchedule `json:"schedule,omitempty"`
	Enabled     *bool            `json:"enabled,omitempty"`
}
