// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Run lifecycle — message_id is a UUID for this run invocation.
// `usage` sums every provider call this run made (tool-loop iterations
// included) — a cost figure, not a context-size one. `context_tokens` is the
// *last* call's prompt size alone (provider-normalized to include any cache
// tokens) — what's actually loaded in the model's context once the run ends.
// `at_ms` is the unix-epoch millisecond the run finished.
type RunCompleteEvent struct {
	MessageID     string `json:"messageId"`
	Usage         Usage  `json:"usage"`
	Iterations    uint32 `json:"iterations"`
	ContextTokens uint32 `json:"contextTokens"`
	AtMs          uint64 `json:"atMs"`
}
