// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Run every matching hook for one server-initiated event inside the sandbox.
type RunHooksRequest struct {
	CallID string          `json:"callId"`
	Event  ServerHookEvent `json:"event"`
}
