// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Every hook that ran, in execution order. Injected context is derived from
// these rather than carried beside them, so no event is recorded specially.
type RunHooksResponse struct {
	CallID  string       `json:"callId"`
	Records []HookRecord `json:"records"`
}
