// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One node of the run graph: a step of the definition, plus every execution
// that landed on it. `runs` is empty for a step the run never reached.
type RunNode struct {
	Step string        `json:"step"`
	Runs []StepRunView `json:"runs"`
}
