// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One edge of the run graph: a transition of the definition, plus which
// executions took it. `traversals` is empty for an edge never taken.
type RunEdge struct {
	From       string   `json:"from"`
	To         string   `json:"to"`
	Condition  *string  `json:"condition,omitempty"`
	Traversals []uint32 `json:"traversals"`
}
