// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type RuntimeVendorInboundMessage struct {
	RequestID string               `json:"requestId"`
	Command   RuntimeVendorCommand `json:"command"`
}
