// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// RuntimeInboundMessageVariant is implemented by every variant of RuntimeInboundMessage.
type RuntimeInboundMessageVariant interface {
	isRuntimeInboundMessageVariant()
}

type RuntimeInboundMessageToolCall struct {
	Value ToolCallRequest
}

func (RuntimeInboundMessageToolCall) isRuntimeInboundMessageVariant() {}

type RuntimeInboundMessageCancelCall struct {
	Value CancelCallRequest
}

func (RuntimeInboundMessageCancelCall) isRuntimeInboundMessageVariant() {}

type RuntimeInboundMessageScanWorkspace struct {
	Value ScanRequest
}

func (RuntimeInboundMessageScanWorkspace) isRuntimeInboundMessageVariant() {}

type RuntimeInboundMessageRunHooks struct {
	Value RunHooksRequest
}

func (RuntimeInboundMessageRunHooks) isRuntimeInboundMessageVariant() {}

type RuntimeInboundMessageMcpDiscover struct {
	Value McpDiscoverRequest
}

func (RuntimeInboundMessageMcpDiscover) isRuntimeInboundMessageVariant() {}

type RuntimeInboundMessageMcpInvoke struct {
	Value McpInvokeRequest
}

func (RuntimeInboundMessageMcpInvoke) isRuntimeInboundMessageVariant() {}

// RuntimeInboundMessage is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type RuntimeInboundMessage struct {
	Variant RuntimeInboundMessageVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u RuntimeInboundMessage) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case RuntimeInboundMessageToolCall:
		return json.Marshal(struct {
			Type  string          `json:"type"`
			Value ToolCallRequest `json:"value"`
		}{"ToolCall", v.Value})
	case RuntimeInboundMessageCancelCall:
		return json.Marshal(struct {
			Type  string            `json:"type"`
			Value CancelCallRequest `json:"value"`
		}{"CancelCall", v.Value})
	case RuntimeInboundMessageScanWorkspace:
		return json.Marshal(struct {
			Type  string      `json:"type"`
			Value ScanRequest `json:"value"`
		}{"ScanWorkspace", v.Value})
	case RuntimeInboundMessageRunHooks:
		return json.Marshal(struct {
			Type  string          `json:"type"`
			Value RunHooksRequest `json:"value"`
		}{"RunHooks", v.Value})
	case RuntimeInboundMessageMcpDiscover:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value McpDiscoverRequest `json:"value"`
		}{"McpDiscover", v.Value})
	case RuntimeInboundMessageMcpInvoke:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value McpInvokeRequest `json:"value"`
		}{"McpInvoke", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: RuntimeInboundMessage has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown RuntimeInboundMessage variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *RuntimeInboundMessage) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "ToolCall":
		var v ToolCallRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeInboundMessageToolCall{Value: v}
		return nil
	case "CancelCall":
		var v CancelCallRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeInboundMessageCancelCall{Value: v}
		return nil
	case "ScanWorkspace":
		var v ScanRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeInboundMessageScanWorkspace{Value: v}
		return nil
	case "RunHooks":
		var v RunHooksRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeInboundMessageRunHooks{Value: v}
		return nil
	case "McpDiscover":
		var v McpDiscoverRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeInboundMessageMcpDiscover{Value: v}
		return nil
	case "McpInvoke":
		var v McpInvokeRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeInboundMessageMcpInvoke{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown RuntimeInboundMessage variant tag %q", envelope.Type)
	}
}
