// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// RuntimeVendorSettingsVariant is implemented by every variant of RuntimeVendorSettings.
type RuntimeVendorSettingsVariant interface {
	isRuntimeVendorSettingsVariant()
}

type RuntimeVendorSettingsFly struct {
	Value FlyVendorSettings
}

func (RuntimeVendorSettingsFly) isRuntimeVendorSettingsVariant() {}

type RuntimeVendorSettingsVelos struct {
	Value VelosVendorSettings
}

func (RuntimeVendorSettingsVelos) isRuntimeVendorSettingsVariant() {}

// Per-kind settings. A union rather than a kind string plus optional structs,
// so a client cannot describe a vendor that has no settings — or two kinds'
// worth.
//
// Adding a kind is a variant here plus a match arm on the server. What each
// substrate can do — Fly keeps a workspace across a hibernate, velos rebuilds
// it — stays inside its implementation and never reaches this type.
// RuntimeVendorSettings is an adjacently tagged union: its JSON carries the variant name
// in "kind" and any payload in "value".
type RuntimeVendorSettings struct {
	Variant RuntimeVendorSettingsVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u RuntimeVendorSettings) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case RuntimeVendorSettingsFly:
		return json.Marshal(struct {
			Type  string            `json:"kind"`
			Value FlyVendorSettings `json:"value"`
		}{"Fly", v.Value})
	case RuntimeVendorSettingsVelos:
		return json.Marshal(struct {
			Type  string              `json:"kind"`
			Value VelosVendorSettings `json:"value"`
		}{"Velos", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: RuntimeVendorSettings has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown RuntimeVendorSettings variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *RuntimeVendorSettings) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"kind"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Fly":
		var v FlyVendorSettings
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorSettingsFly{Value: v}
		return nil
	case "Velos":
		var v VelosVendorSettings
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorSettingsVelos{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown RuntimeVendorSettings variant tag %q", envelope.Type)
	}
}
