// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Runtime summary returned by QueryRuntimes
type RuntimeInfo struct {
	RuntimeID    string       `json:"runtimeId"`
	State        RuntimeState `json:"state"`
	RestartCount uint32       `json:"restartCount"`
}
