// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Announces that the runtime is executing provision steps before Ready. The
// executor extends its handshake deadline and expects Ready or
// ProvisionFailed next on this connection.
type RuntimeProvisioning struct {
	RuntimeID string `json:"runtimeId"`
}
