// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// RuntimeOutboundMessageVariant is implemented by every variant of RuntimeOutboundMessage.
type RuntimeOutboundMessageVariant interface {
	isRuntimeOutboundMessageVariant()
}

type RuntimeOutboundMessageReady struct {
	Value RuntimeReady
}

func (RuntimeOutboundMessageReady) isRuntimeOutboundMessageVariant() {}

type RuntimeOutboundMessageProvisioning struct {
	Value RuntimeProvisioning
}

func (RuntimeOutboundMessageProvisioning) isRuntimeOutboundMessageVariant() {}

type RuntimeOutboundMessageProvisionFailed struct {
	Value RuntimeProvisionFailed
}

func (RuntimeOutboundMessageProvisionFailed) isRuntimeOutboundMessageVariant() {}

type RuntimeOutboundMessageToolCallResponse struct {
	Value ToolCallResponse
}

func (RuntimeOutboundMessageToolCallResponse) isRuntimeOutboundMessageVariant() {}

type RuntimeOutboundMessageScanResult struct {
	Value ScanResponse
}

func (RuntimeOutboundMessageScanResult) isRuntimeOutboundMessageVariant() {}

type RuntimeOutboundMessageHookRecords struct {
	Value RunHooksResponse
}

func (RuntimeOutboundMessageHookRecords) isRuntimeOutboundMessageVariant() {}

type RuntimeOutboundMessageMcpTools struct {
	Value McpDiscoverResponse
}

func (RuntimeOutboundMessageMcpTools) isRuntimeOutboundMessageVariant() {}

type RuntimeOutboundMessageMcpResult struct {
	Value McpInvokeResponse
}

func (RuntimeOutboundMessageMcpResult) isRuntimeOutboundMessageVariant() {}

// All messages the runtime sends to the executor.
// RuntimeOutboundMessage is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type RuntimeOutboundMessage struct {
	Variant RuntimeOutboundMessageVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u RuntimeOutboundMessage) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case RuntimeOutboundMessageReady:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value RuntimeReady `json:"value"`
		}{"Ready", v.Value})
	case RuntimeOutboundMessageProvisioning:
		return json.Marshal(struct {
			Type  string              `json:"type"`
			Value RuntimeProvisioning `json:"value"`
		}{"Provisioning", v.Value})
	case RuntimeOutboundMessageProvisionFailed:
		return json.Marshal(struct {
			Type  string                 `json:"type"`
			Value RuntimeProvisionFailed `json:"value"`
		}{"ProvisionFailed", v.Value})
	case RuntimeOutboundMessageToolCallResponse:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value ToolCallResponse `json:"value"`
		}{"ToolCallResponse", v.Value})
	case RuntimeOutboundMessageScanResult:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value ScanResponse `json:"value"`
		}{"ScanResult", v.Value})
	case RuntimeOutboundMessageHookRecords:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value RunHooksResponse `json:"value"`
		}{"HookRecords", v.Value})
	case RuntimeOutboundMessageMcpTools:
		return json.Marshal(struct {
			Type  string              `json:"type"`
			Value McpDiscoverResponse `json:"value"`
		}{"McpTools", v.Value})
	case RuntimeOutboundMessageMcpResult:
		return json.Marshal(struct {
			Type  string            `json:"type"`
			Value McpInvokeResponse `json:"value"`
		}{"McpResult", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: RuntimeOutboundMessage has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown RuntimeOutboundMessage variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *RuntimeOutboundMessage) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ready":
		var v RuntimeReady
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageReady{Value: v}
		return nil
	case "Provisioning":
		var v RuntimeProvisioning
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageProvisioning{Value: v}
		return nil
	case "ProvisionFailed":
		var v RuntimeProvisionFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageProvisionFailed{Value: v}
		return nil
	case "ToolCallResponse":
		var v ToolCallResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageToolCallResponse{Value: v}
		return nil
	case "ScanResult":
		var v ScanResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageScanResult{Value: v}
		return nil
	case "HookRecords":
		var v RunHooksResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageHookRecords{Value: v}
		return nil
	case "McpTools":
		var v McpDiscoverResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageMcpTools{Value: v}
		return nil
	case "McpResult":
		var v McpInvokeResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeOutboundMessageMcpResult{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown RuntimeOutboundMessage variant tag %q", envelope.Type)
	}
}
