// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// RuntimeStatusVariant is implemented by every variant of RuntimeStatus.
type RuntimeStatusVariant interface {
	isRuntimeStatusVariant()
}

type RuntimeStatusAcquiring struct {
	Value EmptyOutcome
}

func (RuntimeStatusAcquiring) isRuntimeStatusVariant() {}

type RuntimeStatusReady struct {
	Value EmptyOutcome
}

func (RuntimeStatusReady) isRuntimeStatusVariant() {}

type RuntimeStatusFailed struct {
	Value EmptyOutcome
}

func (RuntimeStatusFailed) isRuntimeStatusVariant() {}

// The three states a session's sandbox can be in from an agent's point of
// view. Typed rather than a stage string because a consumer acts on it, and a
// label shared with turn-preparation progress could not be told apart.
// RuntimeStatus is an adjacently tagged union: its JSON carries the variant name
// in "kind" and any payload in "value".
type RuntimeStatus struct {
	Variant RuntimeStatusVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u RuntimeStatus) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case RuntimeStatusAcquiring:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Acquiring", v.Value})
	case RuntimeStatusReady:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Ready", v.Value})
	case RuntimeStatusFailed:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: RuntimeStatus has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown RuntimeStatus variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *RuntimeStatus) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"kind"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Acquiring":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeStatusAcquiring{Value: v}
		return nil
	case "Ready":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeStatusReady{Value: v}
		return nil
	case "Failed":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeStatusFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown RuntimeStatus variant tag %q", envelope.Type)
	}
}
