// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// RuntimeVendorCommandVariant is implemented by every variant of RuntimeVendorCommand.
type RuntimeVendorCommandVariant interface {
	isRuntimeVendorCommandVariant()
}

type RuntimeVendorCommandCreateRuntime struct {
	Value CreateRuntimeRequest
}

func (RuntimeVendorCommandCreateRuntime) isRuntimeVendorCommandVariant() {}

type RuntimeVendorCommandGetRuntime struct {
	Value GetRuntimeRequest
}

func (RuntimeVendorCommandGetRuntime) isRuntimeVendorCommandVariant() {}

type RuntimeVendorCommandHibernateRuntime struct {
	Value HibernateRuntimeRequest
}

func (RuntimeVendorCommandHibernateRuntime) isRuntimeVendorCommandVariant() {}

type RuntimeVendorCommandDeleteRuntime struct {
	Value DeleteRuntimeRequest
}

func (RuntimeVendorCommandDeleteRuntime) isRuntimeVendorCommandVariant() {}

type RuntimeVendorCommandQueryRuntimes struct {
	Value QueryRuntimesRequest
}

func (RuntimeVendorCommandQueryRuntimes) isRuntimeVendorCommandVariant() {}

type RuntimeVendorCommandRuntime struct {
	Value RuntimeRelayRequest
}

func (RuntimeVendorCommandRuntime) isRuntimeVendorCommandVariant() {}

type RuntimeVendorCommandVendorRegistered struct {
	Value VendorRegistered
}

func (RuntimeVendorCommandVendorRegistered) isRuntimeVendorCommandVariant() {}

type RuntimeVendorCommandVendorRejected struct {
	Value VendorRejected
}

func (RuntimeVendorCommandVendorRejected) isRuntimeVendorCommandVariant() {}

// RuntimeVendorCommand is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type RuntimeVendorCommand struct {
	Variant RuntimeVendorCommandVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u RuntimeVendorCommand) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case RuntimeVendorCommandCreateRuntime:
		return json.Marshal(struct {
			Type  string               `json:"type"`
			Value CreateRuntimeRequest `json:"value"`
		}{"CreateRuntime", v.Value})
	case RuntimeVendorCommandGetRuntime:
		return json.Marshal(struct {
			Type  string            `json:"type"`
			Value GetRuntimeRequest `json:"value"`
		}{"GetRuntime", v.Value})
	case RuntimeVendorCommandHibernateRuntime:
		return json.Marshal(struct {
			Type  string                  `json:"type"`
			Value HibernateRuntimeRequest `json:"value"`
		}{"HibernateRuntime", v.Value})
	case RuntimeVendorCommandDeleteRuntime:
		return json.Marshal(struct {
			Type  string               `json:"type"`
			Value DeleteRuntimeRequest `json:"value"`
		}{"DeleteRuntime", v.Value})
	case RuntimeVendorCommandQueryRuntimes:
		return json.Marshal(struct {
			Type  string               `json:"type"`
			Value QueryRuntimesRequest `json:"value"`
		}{"QueryRuntimes", v.Value})
	case RuntimeVendorCommandRuntime:
		return json.Marshal(struct {
			Type  string              `json:"type"`
			Value RuntimeRelayRequest `json:"value"`
		}{"Runtime", v.Value})
	case RuntimeVendorCommandVendorRegistered:
		return json.Marshal(struct {
			Type  string           `json:"type"`
			Value VendorRegistered `json:"value"`
		}{"VendorRegistered", v.Value})
	case RuntimeVendorCommandVendorRejected:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value VendorRejected `json:"value"`
		}{"VendorRejected", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: RuntimeVendorCommand has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown RuntimeVendorCommand variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *RuntimeVendorCommand) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "CreateRuntime":
		var v CreateRuntimeRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandCreateRuntime{Value: v}
		return nil
	case "GetRuntime":
		var v GetRuntimeRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandGetRuntime{Value: v}
		return nil
	case "HibernateRuntime":
		var v HibernateRuntimeRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandHibernateRuntime{Value: v}
		return nil
	case "DeleteRuntime":
		var v DeleteRuntimeRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandDeleteRuntime{Value: v}
		return nil
	case "QueryRuntimes":
		var v QueryRuntimesRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandQueryRuntimes{Value: v}
		return nil
	case "Runtime":
		var v RuntimeRelayRequest
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandRuntime{Value: v}
		return nil
	case "VendorRegistered":
		var v VendorRegistered
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandVendorRegistered{Value: v}
		return nil
	case "VendorRejected":
		var v VendorRejected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorCommandVendorRejected{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown RuntimeVendorCommand variant tag %q", envelope.Type)
	}
}
