// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Whether the session's sandbox exists. A fact about the session, not
// narration: an agent may not start a turn without a runtime, so this is the
// notification that lets one begin.
type RuntimeLifecycle struct {
	Status RuntimeStatus `json:"status"`
	Detail *string       `json:"detail,omitempty"`
}
