// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Provision steps failed; the runtime exits after sending this. `message` is
// surfaced as the create/attach failure reason.
type RuntimeProvisionFailed struct {
	RuntimeID string `json:"runtimeId"`
	Message   string `json:"message"`
}
