// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Everything the server can supply about a runtime. Deliberately minimal:
// anything the vendor knows better (workspace paths, plugin unpack dirs,
// artifact base URLs) is resolved vendor-side and never crosses the wire.
type RuntimeSpec struct {
	// Workspace *names*. The vendor resolves each to a path it owns, and
	// fails the request if it cannot honor one.
	Workspaces []string `json:"workspaces"`
	// Resolved secrets and handles only the server can mint: the scoped
	// GitHub token, the plugin bundle manifest, the plugins token.
	Env []EnvVar `json:"env"`
	// Setup steps the runtime executes before its message loop.
	Provision []ProvisionStep `json:"provision"`
}
