// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A configured runtime vendor as shown to clients.
type RuntimeVendorConfigView struct {
	// The name sessions select by. Exclusive with the names dialled-in vendor
	// agents announce.
	Name     string                `json:"name"`
	Settings RuntimeVendorSettings `json:"settings"`
	// Whether a credential is stored. The token itself never leaves the
	// server — a settings page that could read one back turns every session
	// cookie into a credential exfiltration path.
	HasCredential bool `json:"hasCredential"`
	// Unix epoch seconds.
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
