// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// request_id echoes the request's for responses; a fresh UUID for
// unsolicited announcements (`Ready`, `RuntimeStateChanged`).
type RuntimeVendorOutboundMessage struct {
	RequestID string             `json:"requestId"`
	Event     RuntimeVendorEvent `json:"event"`
}
