// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Create or fully replace a configured runtime vendor.
type RuntimeVendorConfigInput struct {
	Name     string                `json:"name"`
	Settings RuntimeVendorSettings `json:"settings"`
	// Omit to keep the stored token. Required when creating.
	Credential *string `json:"credential,omitempty"`
}
