// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Current lifecycle state of a runtime
type RuntimeState string

const (
	RuntimeStateCreating RuntimeState = "Creating"
	RuntimeStateRunning  RuntimeState = "Running"
	RuntimeStateStopping RuntimeState = "Stopping"
	RuntimeStateStopped  RuntimeState = "Stopped"
	RuntimeStateFailed   RuntimeState = "Failed"
)
