// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// RuntimeVendorEventVariant is implemented by every variant of RuntimeVendorEvent.
type RuntimeVendorEventVariant interface {
	isRuntimeVendorEventVariant()
}

type RuntimeVendorEventReady struct {
	Value RuntimeVendorReady
}

func (RuntimeVendorEventReady) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventCreateRuntime struct {
	Value CreateRuntimeResponse
}

func (RuntimeVendorEventCreateRuntime) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventGetRuntime struct {
	Value GetRuntimeResponse
}

func (RuntimeVendorEventGetRuntime) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventHibernateRuntime struct {
	Value HibernateRuntimeResponse
}

func (RuntimeVendorEventHibernateRuntime) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventDeleteRuntime struct {
	Value DeleteRuntimeResponse
}

func (RuntimeVendorEventDeleteRuntime) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventQueryRuntimes struct {
	Value QueryRuntimesResponse
}

func (RuntimeVendorEventQueryRuntimes) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventRuntime struct {
	Value RuntimeRelayResponse
}

func (RuntimeVendorEventRuntime) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventRequestFailed struct {
	Value RequestFailed
}

func (RuntimeVendorEventRequestFailed) isRuntimeVendorEventVariant() {}

type RuntimeVendorEventRuntimeStateChanged struct {
	Value RuntimeStateChanged
}

func (RuntimeVendorEventRuntimeStateChanged) isRuntimeVendorEventVariant() {}

// RuntimeVendorEvent is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type RuntimeVendorEvent struct {
	Variant RuntimeVendorEventVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u RuntimeVendorEvent) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case RuntimeVendorEventReady:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value RuntimeVendorReady `json:"value"`
		}{"Ready", v.Value})
	case RuntimeVendorEventCreateRuntime:
		return json.Marshal(struct {
			Type  string                `json:"type"`
			Value CreateRuntimeResponse `json:"value"`
		}{"CreateRuntime", v.Value})
	case RuntimeVendorEventGetRuntime:
		return json.Marshal(struct {
			Type  string             `json:"type"`
			Value GetRuntimeResponse `json:"value"`
		}{"GetRuntime", v.Value})
	case RuntimeVendorEventHibernateRuntime:
		return json.Marshal(struct {
			Type  string                   `json:"type"`
			Value HibernateRuntimeResponse `json:"value"`
		}{"HibernateRuntime", v.Value})
	case RuntimeVendorEventDeleteRuntime:
		return json.Marshal(struct {
			Type  string                `json:"type"`
			Value DeleteRuntimeResponse `json:"value"`
		}{"DeleteRuntime", v.Value})
	case RuntimeVendorEventQueryRuntimes:
		return json.Marshal(struct {
			Type  string                `json:"type"`
			Value QueryRuntimesResponse `json:"value"`
		}{"QueryRuntimes", v.Value})
	case RuntimeVendorEventRuntime:
		return json.Marshal(struct {
			Type  string               `json:"type"`
			Value RuntimeRelayResponse `json:"value"`
		}{"Runtime", v.Value})
	case RuntimeVendorEventRequestFailed:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value RequestFailed `json:"value"`
		}{"RequestFailed", v.Value})
	case RuntimeVendorEventRuntimeStateChanged:
		return json.Marshal(struct {
			Type  string              `json:"type"`
			Value RuntimeStateChanged `json:"value"`
		}{"RuntimeStateChanged", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: RuntimeVendorEvent has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown RuntimeVendorEvent variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *RuntimeVendorEvent) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ready":
		var v RuntimeVendorReady
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventReady{Value: v}
		return nil
	case "CreateRuntime":
		var v CreateRuntimeResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventCreateRuntime{Value: v}
		return nil
	case "GetRuntime":
		var v GetRuntimeResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventGetRuntime{Value: v}
		return nil
	case "HibernateRuntime":
		var v HibernateRuntimeResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventHibernateRuntime{Value: v}
		return nil
	case "DeleteRuntime":
		var v DeleteRuntimeResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventDeleteRuntime{Value: v}
		return nil
	case "QueryRuntimes":
		var v QueryRuntimesResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventQueryRuntimes{Value: v}
		return nil
	case "Runtime":
		var v RuntimeRelayResponse
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventRuntime{Value: v}
		return nil
	case "RequestFailed":
		var v RequestFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventRequestFailed{Value: v}
		return nil
	case "RuntimeStateChanged":
		var v RuntimeStateChanged
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = RuntimeVendorEventRuntimeStateChanged{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown RuntimeVendorEvent variant tag %q", envelope.Type)
	}
}
