// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ScanRequest struct {
	CallID                string   `json:"callId"`
	Workspace             *string  `json:"workspace,omitempty"`
	InstructionCandidates []string `json:"instructionCandidates"`
	SkillsGlob            string   `json:"skillsGlob"`
	// When true, also enumerate the shared plugin library and return its skills in
	// `ScanResponse.shared_skills`. The client sets this only for opted-in agents.
	IncludeShared bool `json:"includeShared"`
}
