// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ScanResponse struct {
	CallID       string          `json:"callId"`
	Workspaces   []WorkspaceScan `json:"workspaces"`
	SharedSkills []PluginSkill   `json:"sharedSkills"`
	// Agent definitions from the same library. Optional so an older runtime
	// binary still deserializes against a newer server.
	SharedAgents *[]PluginAgent `json:"sharedAgents,omitempty"`
	// Absolute path of the shared plugin library root, when one is configured
	// and the request asked for it. Optional so an older runtime binary still
	// deserializes against a newer server.
	SharedRoot *string `json:"sharedRoot,omitempty"`
}
