// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// ServerHookEventVariant is implemented by every variant of ServerHookEvent.
type ServerHookEventVariant interface {
	isServerHookEventVariant()
}

type ServerHookEventSessionStart struct {
	Value SessionStartInput
}

func (ServerHookEventSessionStart) isServerHookEventVariant() {}

type ServerHookEventSubagentStart struct {
	Value SubagentStartInput
}

func (ServerHookEventSubagentStart) isServerHookEventVariant() {}

type ServerHookEventUserPromptSubmit struct {
	Value UserPromptSubmitInput
}

func (ServerHookEventUserPromptSubmit) isServerHookEventVariant() {}

type ServerHookEventUserPromptExpansion struct {
	Value UserPromptExpansionInput
}

func (ServerHookEventUserPromptExpansion) isServerHookEventVariant() {}

type ServerHookEventStop struct {
	Value StopInput
}

func (ServerHookEventStop) isServerHookEventVariant() {}

type ServerHookEventSubagentStop struct {
	Value SubagentStopInput
}

func (ServerHookEventSubagentStop) isServerHookEventVariant() {}

// An event the server initiates, carrying that event's input.
//
// Tool events are absent by construction: they run inline in the runtime with
// the call they guard, so asking for one out of band is unrepresentable rather
// than merely wrong. Only wired events have arms — promoting one of the ten
// described-but-unwired events adds its arm here alongside its call site.
// ServerHookEvent is an adjacently tagged union: its JSON carries the variant name
// in "event" and any payload in "value".
type ServerHookEvent struct {
	Variant ServerHookEventVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u ServerHookEvent) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case ServerHookEventSessionStart:
		return json.Marshal(struct {
			Type  string            `json:"event"`
			Value SessionStartInput `json:"value"`
		}{"SessionStart", v.Value})
	case ServerHookEventSubagentStart:
		return json.Marshal(struct {
			Type  string             `json:"event"`
			Value SubagentStartInput `json:"value"`
		}{"SubagentStart", v.Value})
	case ServerHookEventUserPromptSubmit:
		return json.Marshal(struct {
			Type  string                `json:"event"`
			Value UserPromptSubmitInput `json:"value"`
		}{"UserPromptSubmit", v.Value})
	case ServerHookEventUserPromptExpansion:
		return json.Marshal(struct {
			Type  string                   `json:"event"`
			Value UserPromptExpansionInput `json:"value"`
		}{"UserPromptExpansion", v.Value})
	case ServerHookEventStop:
		return json.Marshal(struct {
			Type  string    `json:"event"`
			Value StopInput `json:"value"`
		}{"Stop", v.Value})
	case ServerHookEventSubagentStop:
		return json.Marshal(struct {
			Type  string            `json:"event"`
			Value SubagentStopInput `json:"value"`
		}{"SubagentStop", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: ServerHookEvent has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown ServerHookEvent variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *ServerHookEvent) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"event"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "SessionStart":
		var v SessionStartInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ServerHookEventSessionStart{Value: v}
		return nil
	case "SubagentStart":
		var v SubagentStartInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ServerHookEventSubagentStart{Value: v}
		return nil
	case "UserPromptSubmit":
		var v UserPromptSubmitInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ServerHookEventUserPromptSubmit{Value: v}
		return nil
	case "UserPromptExpansion":
		var v UserPromptExpansionInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ServerHookEventUserPromptExpansion{Value: v}
		return nil
	case "Stop":
		var v StopInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ServerHookEventStop{Value: v}
		return nil
	case "SubagentStop":
		var v SubagentStopInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ServerHookEventSubagentStop{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown ServerHookEvent variant tag %q", envelope.Type)
	}
}
