// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Read-only deployment paths and version, for transparency. `config_path` is
// the deployment config file (config.json); `database` is where the editable
// settings above are stored — the two never overlap.
type ServerInfo struct {
	ConfigPath string `json:"configPath"`
	Database   string `json:"database"`
	StateDir   string `json:"stateDir"`
	DataDir    string `json:"dataDir"`
	PluginsDir string `json:"pluginsDir"`
	Version    string `json:"version"`
}
