// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `source` is the matcher domain, and the record keeps the wire spelling the
// hook was given rather than the enum: this is what the transcript shows.
type SessionStartRecord struct {
	Source        string              `json:"source"`
	SystemMessage *string             `json:"systemMessage,omitempty"`
	Outcome       SessionStartOutcome `json:"outcome"`
}
