// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// User-visible lifecycle state of a session. Failure reasons ride separately
// in `last_error` so the enum stays a plain discriminant.
type SessionStatusKind string

const (
	// The runtime is being built. A session is created in this state and
	// leaves it once its vendor confirms the runtime; anything sent
	// meanwhile is queued and runs as soon as it does.
	SessionStatusKindProvisioning  SessionStatusKind = "Provisioning"
	SessionStatusKindIdle          SessionStatusKind = "Idle"
	SessionStatusKindRunning       SessionStatusKind = "Running"
	SessionStatusKindAwaitingInput SessionStatusKind = "AwaitingInput"
	// A workflow run completed with no error. Not terminal: a retry or a new
	// message moves it back to `Running`.
	SessionStatusKindFinished      SessionStatusKind = "Finished"
	SessionStatusKindFailed        SessionStatusKind = "Failed"
	SessionStatusKindUnrecoverable SessionStatusKind = "Unrecoverable"
)
