// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `reason` is the matcher domain: clear | resume | logout | prompt_input_exit | …
type SessionEndRecord struct {
	Reason  string            `json:"reason"`
	Outcome SideEffectOutcome `json:"outcome"`
}
