// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// SessionStartSourceVariant is implemented by every variant of SessionStartSource.
type SessionStartSourceVariant interface {
	isSessionStartSourceVariant()
}

type SessionStartSourceStartup struct{}

func (SessionStartSourceStartup) isSessionStartSourceVariant() {}

type SessionStartSourceResume struct{}

func (SessionStartSourceResume) isSessionStartSourceVariant() {}

type SessionStartSourceClear struct{}

func (SessionStartSourceClear) isSessionStartSourceVariant() {}

type SessionStartSourceCompact struct{}

func (SessionStartSourceCompact) isSessionStartSourceVariant() {}

type SessionStartSourceFork struct{}

func (SessionStartSourceFork) isSessionStartSourceVariant() {}

// How the session that is starting came to start.
//
// The spec's whole vocabulary, not the subset horsie produces. `Clear`,
// `Compact` and `Fork` have no call site — horsie has no fork and no clear,
// and although it does compact, it deliberately does not re-fire
// `SessionStart` afterwards: `PostCompact` already covers reacting to one, and
// re-running every session-start hook for something that is not a session
// start would be a second, worse way to say the same thing. They are arms
// nothing constructs rather than values that silently never appear, which is
// the same honesty `is_wired()` gives an event horsie cannot fire. A matcher
// on one of them selects nothing.
// SessionStartSource is an adjacently tagged union: its JSON carries the variant name
// in "source" and any payload in "value".
type SessionStartSource struct {
	Variant SessionStartSourceVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u SessionStartSource) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case SessionStartSourceStartup:
		return json.Marshal(struct {
			Type string `json:"source"`
		}{"Startup"})
	case SessionStartSourceResume:
		return json.Marshal(struct {
			Type string `json:"source"`
		}{"Resume"})
	case SessionStartSourceClear:
		return json.Marshal(struct {
			Type string `json:"source"`
		}{"Clear"})
	case SessionStartSourceCompact:
		return json.Marshal(struct {
			Type string `json:"source"`
		}{"Compact"})
	case SessionStartSourceFork:
		return json.Marshal(struct {
			Type string `json:"source"`
		}{"Fork"})
	case nil:
		return nil, fmt.Errorf("fluorite: SessionStartSource has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown SessionStartSource variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *SessionStartSource) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"source"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Startup":
		u.Variant = SessionStartSourceStartup{}
		return nil
	case "Resume":
		u.Variant = SessionStartSourceResume{}
		return nil
	case "Clear":
		u.Variant = SessionStartSourceClear{}
		return nil
	case "Compact":
		u.Variant = SessionStartSourceCompact{}
		return nil
	case "Fork":
		u.Variant = SessionStartSourceFork{}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown SessionStartSource variant tag %q", envelope.Type)
	}
}
