// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// SessionStartOutcomeVariant is implemented by every variant of SessionStartOutcome.
type SessionStartOutcomeVariant interface {
	isSessionStartOutcomeVariant()
}

type SessionStartOutcomeRan struct {
	Value ContextInjected
}

func (SessionStartOutcomeRan) isSessionStartOutcomeVariant() {}

type SessionStartOutcomeFailed struct {
	Value HookFailed
}

func (SessionStartOutcomeFailed) isSessionStartOutcomeVariant() {}

// Cannot block: `SessionStart` has no decision field, because by the time it
// runs there is nothing to refuse.
// SessionStartOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type SessionStartOutcome struct {
	Variant SessionStartOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u SessionStartOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case SessionStartOutcomeRan:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value ContextInjected `json:"value"`
		}{"Ran", v.Value})
	case SessionStartOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: SessionStartOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown SessionStartOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *SessionStartOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v ContextInjected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SessionStartOutcomeRan{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SessionStartOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown SessionStartOutcome variant tag %q", envelope.Type)
	}
}
