// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type SessionSummary struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
	// What the session last reported. Always known: the registry keeps a
	// durable copy, so a cold session answers without being loaded.
	Status    SessionStatusKind `json:"status"`
	CreatedAt uint64            `json:"createdAt"`
	LastError *string           `json:"lastError,omitempty"`
	// The workflow this session is a run of. Present only for a run, which is
	// what lets the session list annotate one without a second request.
	// Routine runs carry nothing here — they are not in the list at all.
	Workflow *string `json:"workflow,omitempty"`
	// User-set key-value metadata (e.g. `group=<name>`). Empty when none.
	Annotations []AnnotationEntry `json:"annotations"`
	// The conversations forked out of this session, so a list can nest them
	// under it. Flat and parent-linked rather than already nested, because the
	// registry holds it flat — and answered from that registry, so listing
	// sessions still loads none of them.
	Forks []ForkView `json:"forks"`
}
