// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type SessionSummary struct {
	ID   string  `json:"id"`
	Name *string `json:"name,omitempty"`
	// Absent when the session is not loaded: the server does not guess, and
	// a restart leaves every row unknown until one is opened.
	Status    *SessionStatusKind `json:"status,omitempty"`
	CreatedAt uint64             `json:"createdAt"`
	LastError *string            `json:"lastError,omitempty"`
	// The workflow this session is a run of. Present only for a run, which is
	// what lets the session list annotate one without a second request.
	// Routine runs carry nothing here — they are not in the list at all.
	Workflow *string `json:"workflow,omitempty"`
	// User-set key-value metadata (e.g. `group=<name>`). Empty when none.
	Annotations []AnnotationEntry `json:"annotations"`
}
