// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Acknowledges an accepted user message. The id is how a client matches its
// optimistic bubble to the queued message the server now owes an answer for.
type SessionAck struct {
	MessageID string `json:"messageId"`
}
