// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A registered session group. Groups may exist with zero sessions; a group
// referenced only by annotations is not registered but still lists.
type SessionGroupView struct {
	Name string `json:"name"`
}
