// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Merge-update a session's annotations: every `set` entry upserts a key,
// every `remove` entry drops one. Keys not mentioned are untouched.
type SetAnnotationsRequest struct {
	Set    []AnnotationEntry `json:"set"`
	Remove []string          `json:"remove"`
}
