// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Replace the runtime-editable settings. Each present field fully replaces
// that section; an omitted (null) field leaves it unchanged. Vendors are
// absent by design: they are connected agents, configured in their own
// processes, so there is nothing here to persist.
type SettingsUpdate struct {
	Providers     *[]ProviderInput `json:"providers,omitempty"`
	Models        *[]ModelInput    `json:"models,omitempty"`
	DefaultVendor *string          `json:"defaultVendor,omitempty"`
}
