// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Full settings snapshot — returned by `GET /api/config` and after an update.
type SettingsView struct {
	Providers     []ProviderView `json:"providers"`
	Models        []ModelView    `json:"models"`
	Vendors       []VendorView   `json:"vendors"`
	DefaultVendor string         `json:"defaultVendor"`
	Info          ServerInfo     `json:"info"`
	// Always false: every provider/model edit applies live. Retained for wire
	// compatibility.
	RestartRequired bool `json:"restartRequired"`
}
