// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// SideEffectOutcomeVariant is implemented by every variant of SideEffectOutcome.
type SideEffectOutcomeVariant interface {
	isSideEffectOutcomeVariant()
}

type SideEffectOutcomeRan struct{}

func (SideEffectOutcomeRan) isSideEffectOutcomeVariant() {}

type SideEffectOutcomeFailed struct {
	Value HookFailed
}

func (SideEffectOutcomeFailed) isSideEffectOutcomeVariant() {}

// These support no JSON output at all — not even `systemMessage` — and cannot
// block: exit 2 has no special meaning for them. They can still fail, and
// their stderr is still user-facing, which is the whole of what to record.
// SideEffectOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type SideEffectOutcome struct {
	Variant SideEffectOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u SideEffectOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case SideEffectOutcomeRan:
		return json.Marshal(struct {
			Type string `json:"outcome"`
		}{"Ran"})
	case SideEffectOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: SideEffectOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown SideEffectOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *SideEffectOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		u.Variant = SideEffectOutcomeRan{}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SideEffectOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown SideEffectOutcome variant tag %q", envelope.Type)
	}
}
