// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One value a step's `outcome` may take, and what choosing it means.
//
// The description is not decoration: it is what the model reads to pick
// between values, and it is the only thing standing between "failure" meaning
// *the work failed* and meaning *I could not finish*.
type StepOutcome struct {
	Value       string `json:"value"`
	Description string `json:"description"`
}
