// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One field a step's result carries beyond `outcome` and `description`.
type StepField struct {
	Name string        `json:"name"`
	Kind StepFieldType `json:"kind"`
	// Required. An undocumented field is one the model fills in by guessing.
	Description string `json:"description"`
	// Whether the step must always supply it. Absent → optional.
	Required *bool `json:"required,omitempty"`
}
