// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The type of one declared result field.
type StepFieldType string

const (
	StepFieldTypeString     StepFieldType = "String"
	StepFieldTypeNumber     StepFieldType = "Number"
	StepFieldTypeBoolean    StepFieldType = "Boolean"
	StepFieldTypeStringList StepFieldType = "StringList"
)
