// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// StepRunStatusVariant is implemented by every variant of StepRunStatus.
type StepRunStatusVariant interface {
	isStepRunStatusVariant()
}

type StepRunStatusRunning struct {
	Value StepRunning
}

func (StepRunStatusRunning) isStepRunStatusVariant() {}

type StepRunStatusConcluded struct {
	Value StepConcluded
}

func (StepRunStatusConcluded) isStepRunStatusVariant() {}

type StepRunStatusFailed struct {
	Value StepFailed
}

func (StepRunStatusFailed) isStepRunStatusVariant() {}

type StepRunStatusCancelled struct {
	Value StepCancelled
}

func (StepRunStatusCancelled) isStepRunStatusVariant() {}

// What became of one step execution.
// StepRunStatus is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type StepRunStatus struct {
	Variant StepRunStatusVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u StepRunStatus) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case StepRunStatusRunning:
		return json.Marshal(struct {
			Type  string      `json:"type"`
			Value StepRunning `json:"value"`
		}{"Running", v.Value})
	case StepRunStatusConcluded:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value StepConcluded `json:"value"`
		}{"Concluded", v.Value})
	case StepRunStatusFailed:
		return json.Marshal(struct {
			Type  string     `json:"type"`
			Value StepFailed `json:"value"`
		}{"Failed", v.Value})
	case StepRunStatusCancelled:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value StepCancelled `json:"value"`
		}{"Cancelled", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: StepRunStatus has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown StepRunStatus variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *StepRunStatus) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Running":
		var v StepRunning
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StepRunStatusRunning{Value: v}
		return nil
	case "Concluded":
		var v StepConcluded
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StepRunStatusConcluded{Value: v}
		return nil
	case "Failed":
		var v StepFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StepRunStatusFailed{Value: v}
		return nil
	case "Cancelled":
		var v StepCancelled
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StepRunStatusCancelled{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown StepRunStatus variant tag %q", envelope.Type)
	}
}
