// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One execution of one step. A step visited twice — by a loop or by a retry —
// has two of these.
type StepRunView struct {
	// Position in the run log; the id a retry names.
	Index uint32 `json:"index"`
	// Which step of the definition ran.
	Step string `json:"step"`
	// The agent this execution is, addressable at
	// `/sessions/:id/agents/:agent_id`.
	AgentID string `json:"agentId"`
	// 1 for the first execution of this step on this path.
	Attempt uint32        `json:"attempt"`
	Status  StepRunStatus `json:"status"`
	// The structured output it concluded with.
	Output      *any    `json:"output,omitempty"`
	Error       *string `json:"error,omitempty"`
	StartedAtMs uint64  `json:"startedAtMs"`
	EndedAtMs   *uint64 `json:"endedAtMs,omitempty"`
	// Tokens this execution spent.
	InputTokens  uint32 `json:"inputTokens"`
	OutputTokens uint32 `json:"outputTokens"`
}
