// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One workflow step's progress, recorded on that step's own agent. Carries the
// step's `name` as well as its index: the index identifies the execution, but
// the name is what a person reading the run recognises.
type StepLifecycle struct {
	Index  uint32 `json:"index"`
	Name   string `json:"name"`
	Status string `json:"status"`
}
