// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// StopOutcomeVariant is implemented by every variant of StopOutcome.
type StopOutcomeVariant interface {
	isStopOutcomeVariant()
}

type StopOutcomeRan struct {
	Value ContextInjected
}

func (StopOutcomeRan) isStopOutcomeVariant() {}

type StopOutcomeBlocked struct {
	Value HookBlocked
}

func (StopOutcomeBlocked) isStopOutcomeVariant() {}

type StopOutcomeFailed struct {
	Value HookFailed
}

func (StopOutcomeFailed) isStopOutcomeVariant() {}

type StopOutcomeCapReached struct {
	Value HookBlocked
}

func (StopOutcomeCapReached) isStopOutcomeVariant() {}

// StopOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type StopOutcome struct {
	Variant StopOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u StopOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case StopOutcomeRan:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value ContextInjected `json:"value"`
		}{"Ran", v.Value})
	case StopOutcomeBlocked:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"Blocked", v.Value})
	case StopOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case StopOutcomeCapReached:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"CapReached", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: StopOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown StopOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *StopOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v ContextInjected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StopOutcomeRan{Value: v}
		return nil
	case "Blocked":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StopOutcomeBlocked{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StopOutcomeFailed{Value: v}
		return nil
	case "CapReached":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = StopOutcomeCapReached{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown StopOutcome variant tag %q", envelope.Type)
	}
}
