// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `error` is the matcher domain: rate_limit | overloaded | … | unknown
type StopFailureRecord struct {
	Error   string            `json:"error"`
	Outcome SideEffectOutcome `json:"outcome"`
}
