// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One agent this session hosts. The main agent has `parent`/`label` absent
// and `depth` 0; subagents carry their spawn metadata. `output` and the full
// transcript live on the agent document and its history, not here.
type SubAgentView struct {
	ID string `json:"id"`
	// Parent agent id; absent → the session's main agent.
	Parent *string `json:"parent,omitempty"`
	Label  *string `json:"label,omitempty"`
	Depth  uint32  `json:"depth"`
	// The plugin-declared agent type this subagent runs as, when it was
	// spawned with one. Absent for the main agent and for a general-purpose
	// subagent.
	AgentType *string `json:"agentType,omitempty"`
	// "running" | "completed" | "failed".
	Status string  `json:"status"`
	Error  *string `json:"error,omitempty"`
	// When this agent was spawned and when it reached its current result.
	// Zero when unrecorded — journaled before these were kept, or (for
	// `ended_at_ms`) still running.
	SpawnedAtMs uint64 `json:"spawnedAtMs"`
	EndedAtMs   uint64 `json:"endedAtMs"`
}
