// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A subagent this agent spawned, and where it got to. Recorded on the
// *parent*, because the parent is what a viewer is reading when it matters.
type SubAgentLifecycle struct {
	ID     string `json:"id"`
	Label  string `json:"label"`
	Status string `json:"status"`
}
