// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// SubagentStartOutcomeVariant is implemented by every variant of SubagentStartOutcome.
type SubagentStartOutcomeVariant interface {
	isSubagentStartOutcomeVariant()
}

type SubagentStartOutcomeRan struct {
	Value ContextInjected
}

func (SubagentStartOutcomeRan) isSubagentStartOutcomeVariant() {}

type SubagentStartOutcomeFailed struct {
	Value HookFailed
}

func (SubagentStartOutcomeFailed) isSubagentStartOutcomeVariant() {}

// SubagentStartOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type SubagentStartOutcome struct {
	Variant SubagentStartOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u SubagentStartOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case SubagentStartOutcomeRan:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value ContextInjected `json:"value"`
		}{"Ran", v.Value})
	case SubagentStartOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: SubagentStartOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown SubagentStartOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *SubagentStartOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v ContextInjected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SubagentStartOutcomeRan{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SubagentStartOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown SubagentStartOutcome variant tag %q", envelope.Type)
	}
}
