// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type SubagentStartRecord struct {
	AgentID       string               `json:"agentId"`
	AgentType     string               `json:"agentType"`
	SystemMessage *string              `json:"systemMessage,omitempty"`
	Outcome       SubagentStartOutcome `json:"outcome"`
}
