// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// SubagentStopOutcomeVariant is implemented by every variant of SubagentStopOutcome.
type SubagentStopOutcomeVariant interface {
	isSubagentStopOutcomeVariant()
}

type SubagentStopOutcomeRan struct {
	Value ContextInjected
}

func (SubagentStopOutcomeRan) isSubagentStopOutcomeVariant() {}

type SubagentStopOutcomeBlocked struct {
	Value HookBlocked
}

func (SubagentStopOutcomeBlocked) isSubagentStopOutcomeVariant() {}

type SubagentStopOutcomeFailed struct {
	Value HookFailed
}

func (SubagentStopOutcomeFailed) isSubagentStopOutcomeVariant() {}

type SubagentStopOutcomeCapReached struct {
	Value HookBlocked
}

func (SubagentStopOutcomeCapReached) isSubagentStopOutcomeVariant() {}

// SubagentStopOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type SubagentStopOutcome struct {
	Variant SubagentStopOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u SubagentStopOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case SubagentStopOutcomeRan:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value ContextInjected `json:"value"`
		}{"Ran", v.Value})
	case SubagentStopOutcomeBlocked:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"Blocked", v.Value})
	case SubagentStopOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case SubagentStopOutcomeCapReached:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"CapReached", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: SubagentStopOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown SubagentStopOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *SubagentStopOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v ContextInjected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SubagentStopOutcomeRan{Value: v}
		return nil
	case "Blocked":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SubagentStopOutcomeBlocked{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SubagentStopOutcomeFailed{Value: v}
		return nil
	case "CapReached":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = SubagentStopOutcomeCapReached{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown SubagentStopOutcome variant tag %q", envelope.Type)
	}
}
