// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A subagent's turn ending. Carries the same pair `SubagentStart` does, so a
// hook can join its own start to its own stop.
type SubagentStopInput struct {
	AgentID              string  `json:"agentId"`
	AgentType            string  `json:"agentType"`
	LastAssistantMessage *string `json:"lastAssistantMessage,omitempty"`
	StopHookActive       bool    `json:"stopHookActive"`
}
