// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type SubagentStopRecord struct {
	AgentID       string              `json:"agentId"`
	AgentType     string              `json:"agentType"`
	SystemMessage *string             `json:"systemMessage,omitempty"`
	Outcome       SubagentStopOutcome `json:"outcome"`
}
