// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The agent's `task_list` state, whole. Both the current value and the
// notification that it changed — a client folds it, last one wins.
type TaskListLifecycle struct {
	Tasks []TaskItem `json:"tasks"`
}
