// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// TaskOutcomeVariant is implemented by every variant of TaskOutcome.
type TaskOutcomeVariant interface {
	isTaskOutcomeVariant()
}

type TaskOutcomeRan struct{}

func (TaskOutcomeRan) isTaskOutcomeVariant() {}

type TaskOutcomeFailed struct {
	Value HookFailed
}

func (TaskOutcomeFailed) isTaskOutcomeVariant() {}

// TaskOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type TaskOutcome struct {
	Variant TaskOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u TaskOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case TaskOutcomeRan:
		return json.Marshal(struct {
			Type string `json:"outcome"`
		}{"Ran"})
	case TaskOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: TaskOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown TaskOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *TaskOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		u.Variant = TaskOutcomeRan{}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = TaskOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown TaskOutcome variant tag %q", envelope.Type)
	}
}
