// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Status of one entry in the agent's `task_list` tool state.
type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "Pending"
	TaskStatusInProgress TaskStatus = "InProgress"
	TaskStatusCompleted  TaskStatus = "Completed"
)
