// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type TaskCreatedRecord struct {
	TaskID        string      `json:"taskId"`
	SystemMessage *string     `json:"systemMessage,omitempty"`
	Outcome       TaskOutcome `json:"outcome"`
}
