// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One entry in the agent's `task_list` tool state.
type TaskItem struct {
	ID      uint32     `json:"id"`
	Content string     `json:"content"`
	Status  TaskStatus `json:"status"`
}
