// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ThinkingChunkEvent struct {
	MessageID string `json:"messageId"`
	Index     uint32 `json:"index"`
	Text      string `json:"text"`
}
