// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Extended thinking content
type ThinkingPart struct {
	Text      string  `json:"text"`
	Signature *string `json:"signature,omitempty"`
}
