// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ThinkingSignatureChunkEvent struct {
	MessageID string `json:"messageId"`
	Index     uint32 `json:"index"`
	Signature string `json:"signature"`
}
