// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// An access token and the refresh token that replaces it. The refresh token
// rotates on every use.
type TokenPair struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	// Seconds until the access token expires.
	ExpiresIn uint32 `json:"expiresIn"`
}
