// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `at_ms` is the unix-epoch millisecond the tool finished. It rides on the
// event so the tool-result message held in memory and the one folded from the
// journal carry the identical stamp — read the clock twice and a replayed
// transcript would disagree with the live one.
type ToolCompleteEvent struct {
	MessageID  string `json:"messageId"`
	ToolCallID string `json:"toolCallId"`
	Output     string `json:"output"`
	IsError    bool   `json:"isError"`
	AtMs       uint64 `json:"atMs"`
}
