// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// ToolCallVariant is implemented by every variant of ToolCall.
type ToolCallVariant interface {
	isToolCallVariant()
}

type ToolCallBash struct {
	Value BashInput
}

func (ToolCallBash) isToolCallVariant() {}

type ToolCallReadFile struct {
	Value ReadFileInput
}

func (ToolCallReadFile) isToolCallVariant() {}

type ToolCallWriteFile struct {
	Value WriteFileInput
}

func (ToolCallWriteFile) isToolCallVariant() {}

type ToolCallFindAndReplace struct {
	Value FindAndReplaceInput
}

func (ToolCallFindAndReplace) isToolCallVariant() {}

type ToolCallReplaceLines struct {
	Value ReplaceLinesInput
}

func (ToolCallReplaceLines) isToolCallVariant() {}

type ToolCallListFiles struct {
	Value ListFilesInput
}

func (ToolCallListFiles) isToolCallVariant() {}

type ToolCallGlob struct {
	Value GlobInput
}

func (ToolCallGlob) isToolCallVariant() {}

type ToolCallGrep struct {
	Value GrepInput
}

func (ToolCallGrep) isToolCallVariant() {}

type ToolCallSetWorkingDir struct {
	Value SetWorkingDirInput
}

func (ToolCallSetWorkingDir) isToolCallVariant() {}

type ToolCallSetEnv struct {
	Value SetEnvInput
}

func (ToolCallSetEnv) isToolCallVariant() {}

// One variant per tool. The tag doubles as the tool name seen by the LLM.
// ToolCall is an adjacently tagged union: its JSON carries the variant name
// in "tool" and any payload in "value".
type ToolCall struct {
	Variant ToolCallVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u ToolCall) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case ToolCallBash:
		return json.Marshal(struct {
			Type  string    `json:"tool"`
			Value BashInput `json:"value"`
		}{"Bash", v.Value})
	case ToolCallReadFile:
		return json.Marshal(struct {
			Type  string        `json:"tool"`
			Value ReadFileInput `json:"value"`
		}{"ReadFile", v.Value})
	case ToolCallWriteFile:
		return json.Marshal(struct {
			Type  string         `json:"tool"`
			Value WriteFileInput `json:"value"`
		}{"WriteFile", v.Value})
	case ToolCallFindAndReplace:
		return json.Marshal(struct {
			Type  string              `json:"tool"`
			Value FindAndReplaceInput `json:"value"`
		}{"FindAndReplace", v.Value})
	case ToolCallReplaceLines:
		return json.Marshal(struct {
			Type  string            `json:"tool"`
			Value ReplaceLinesInput `json:"value"`
		}{"ReplaceLines", v.Value})
	case ToolCallListFiles:
		return json.Marshal(struct {
			Type  string         `json:"tool"`
			Value ListFilesInput `json:"value"`
		}{"ListFiles", v.Value})
	case ToolCallGlob:
		return json.Marshal(struct {
			Type  string    `json:"tool"`
			Value GlobInput `json:"value"`
		}{"Glob", v.Value})
	case ToolCallGrep:
		return json.Marshal(struct {
			Type  string    `json:"tool"`
			Value GrepInput `json:"value"`
		}{"Grep", v.Value})
	case ToolCallSetWorkingDir:
		return json.Marshal(struct {
			Type  string             `json:"tool"`
			Value SetWorkingDirInput `json:"value"`
		}{"SetWorkingDir", v.Value})
	case ToolCallSetEnv:
		return json.Marshal(struct {
			Type  string      `json:"tool"`
			Value SetEnvInput `json:"value"`
		}{"SetEnv", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: ToolCall has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown ToolCall variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *ToolCall) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"tool"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Bash":
		var v BashInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallBash{Value: v}
		return nil
	case "ReadFile":
		var v ReadFileInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallReadFile{Value: v}
		return nil
	case "WriteFile":
		var v WriteFileInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallWriteFile{Value: v}
		return nil
	case "FindAndReplace":
		var v FindAndReplaceInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallFindAndReplace{Value: v}
		return nil
	case "ReplaceLines":
		var v ReplaceLinesInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallReplaceLines{Value: v}
		return nil
	case "ListFiles":
		var v ListFilesInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallListFiles{Value: v}
		return nil
	case "Glob":
		var v GlobInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallGlob{Value: v}
		return nil
	case "Grep":
		var v GrepInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallGrep{Value: v}
		return nil
	case "SetWorkingDir":
		var v SetWorkingDirInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallSetWorkingDir{Value: v}
		return nil
	case "SetEnv":
		var v SetEnvInput
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = ToolCallSetEnv{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown ToolCall variant tag %q", envelope.Type)
	}
}
