// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Tool execution — message_id is the tool-result message id ("result:<tool_call_id>")
type ToolExecutingEvent struct {
	MessageID  string `json:"messageId"`
	ToolCallID string `json:"toolCallId"`
}
