// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ToolCallResponse struct {
	CallID string     `json:"callId"`
	Result ToolResult `json:"result"`
	// Every hook that ran for this call, in execution order. Empty for the
	// overwhelmingly common case of a session with no matching hooks.
	Hooks []HookRecord `json:"hooks"`
}
