// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ToolCallStartEvent struct {
	MessageID  string `json:"messageId"`
	Index      uint32 `json:"index"`
	ToolCallID string `json:"toolCallId"`
	Name       string `json:"name"`
}
