// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// What a tool hook guarded. The join key attaching a record to its call.
type ToolScope struct {
	Tool       string `json:"tool"`
	ToolCallID string `json:"toolCallId"`
}
