// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A tool call requested by the model
type ToolCallPart struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Input any    `json:"input"`
}
