// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type ToolCallInputDeltaEvent struct {
	MessageID  string `json:"messageId"`
	Index      uint32 `json:"index"`
	ToolCallID string `json:"toolCallId"`
	Delta      string `json:"delta"`
}
