// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// TurnOutcomeVariant is implemented by every variant of TurnOutcome.
type TurnOutcomeVariant interface {
	isTurnOutcomeVariant()
}

type TurnOutcomeEnded struct {
	Value EmptyOutcome
}

func (TurnOutcomeEnded) isTurnOutcomeVariant() {}

type TurnOutcomeFailed struct {
	Value FailedOutcome
}

func (TurnOutcomeFailed) isTurnOutcomeVariant() {}

type TurnOutcomeStopped struct {
	Value EmptyOutcome
}

func (TurnOutcomeStopped) isTurnOutcomeVariant() {}

type TurnOutcomeInterrupted struct {
	Value EmptyOutcome
}

func (TurnOutcomeInterrupted) isTurnOutcomeVariant() {}

// How a turn ended. One entry with an outcome rather than four sibling
// lifecycle variants: every consumer that cares about "the turn is over"
// should not have to enumerate the ways.
// TurnOutcome is an adjacently tagged union: its JSON carries the variant name
// in "kind" and any payload in "value".
type TurnOutcome struct {
	Variant TurnOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u TurnOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case TurnOutcomeEnded:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Ended", v.Value})
	case TurnOutcomeFailed:
		return json.Marshal(struct {
			Type  string        `json:"kind"`
			Value FailedOutcome `json:"value"`
		}{"Failed", v.Value})
	case TurnOutcomeStopped:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Stopped", v.Value})
	case TurnOutcomeInterrupted:
		return json.Marshal(struct {
			Type  string       `json:"kind"`
			Value EmptyOutcome `json:"value"`
		}{"Interrupted", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: TurnOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown TurnOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *TurnOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"kind"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ended":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = TurnOutcomeEnded{Value: v}
		return nil
	case "Failed":
		var v FailedOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = TurnOutcomeFailed{Value: v}
		return nil
	case "Stopped":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = TurnOutcomeStopped{Value: v}
		return nil
	case "Interrupted":
		var v EmptyOutcome
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = TurnOutcomeInterrupted{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown TurnOutcome variant tag %q", envelope.Type)
	}
}
