// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A turn started, consuming these queued message ids and answering these asks.
type TurnBeganLifecycle struct {
	Consumed []string `json:"consumed"`
	Answered []string `json:"answered"`
}
