// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Cumulative token usage across a session's completed turns. `u64` (not the
// per-turn `Usage`'s `u32`) because it sums re-sent context over many turns.
// Cache fields are `Option<u64>`, absent only when no completed turn ever
// reported cache data — never coerced to a fake zero.
type UsageView struct {
	InputTokens         uint64  `json:"inputTokens"`
	OutputTokens        uint64  `json:"outputTokens"`
	CacheCreationTokens *uint64 `json:"cacheCreationTokens,omitempty"`
	CacheReadTokens     *uint64 `json:"cacheReadTokens,omitempty"`
}
