// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Injects context via raw stdout as well as `additionalContext`.
type UserPromptSubmitRecord struct {
	SystemMessage *string                 `json:"systemMessage,omitempty"`
	Outcome       UserPromptSubmitOutcome `json:"outcome"`
}
