// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// UserPromptExpansionOutcomeVariant is implemented by every variant of UserPromptExpansionOutcome.
type UserPromptExpansionOutcomeVariant interface {
	isUserPromptExpansionOutcomeVariant()
}

type UserPromptExpansionOutcomeRan struct {
	Value ContextInjected
}

func (UserPromptExpansionOutcomeRan) isUserPromptExpansionOutcomeVariant() {}

type UserPromptExpansionOutcomeBlocked struct {
	Value HookBlocked
}

func (UserPromptExpansionOutcomeBlocked) isUserPromptExpansionOutcomeVariant() {}

type UserPromptExpansionOutcomeFailed struct {
	Value HookFailed
}

func (UserPromptExpansionOutcomeFailed) isUserPromptExpansionOutcomeVariant() {}

// UserPromptExpansionOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type UserPromptExpansionOutcome struct {
	Variant UserPromptExpansionOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u UserPromptExpansionOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case UserPromptExpansionOutcomeRan:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value ContextInjected `json:"value"`
		}{"Ran", v.Value})
	case UserPromptExpansionOutcomeBlocked:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"Blocked", v.Value})
	case UserPromptExpansionOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: UserPromptExpansionOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown UserPromptExpansionOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *UserPromptExpansionOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v ContextInjected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = UserPromptExpansionOutcomeRan{Value: v}
		return nil
	case "Blocked":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = UserPromptExpansionOutcomeBlocked{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = UserPromptExpansionOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown UserPromptExpansionOutcome variant tag %q", envelope.Type)
	}
}
