// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// `command` is the matcher domain: the name being expanded, so a hook can
// guard one command rather than every prompt.
type UserPromptExpansionRecord struct {
	Command       string                     `json:"command"`
	SystemMessage *string                    `json:"systemMessage,omitempty"`
	Outcome       UserPromptExpansionOutcome `json:"outcome"`
}
