// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// UserPromptSubmitOutcomeVariant is implemented by every variant of UserPromptSubmitOutcome.
type UserPromptSubmitOutcomeVariant interface {
	isUserPromptSubmitOutcomeVariant()
}

type UserPromptSubmitOutcomeRan struct {
	Value ContextInjected
}

func (UserPromptSubmitOutcomeRan) isUserPromptSubmitOutcomeVariant() {}

type UserPromptSubmitOutcomeBlocked struct {
	Value HookBlocked
}

func (UserPromptSubmitOutcomeBlocked) isUserPromptSubmitOutcomeVariant() {}

type UserPromptSubmitOutcomeFailed struct {
	Value HookFailed
}

func (UserPromptSubmitOutcomeFailed) isUserPromptSubmitOutcomeVariant() {}

// UserPromptSubmitOutcome is an adjacently tagged union: its JSON carries the variant name
// in "outcome" and any payload in "value".
type UserPromptSubmitOutcome struct {
	Variant UserPromptSubmitOutcomeVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u UserPromptSubmitOutcome) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case UserPromptSubmitOutcomeRan:
		return json.Marshal(struct {
			Type  string          `json:"outcome"`
			Value ContextInjected `json:"value"`
		}{"Ran", v.Value})
	case UserPromptSubmitOutcomeBlocked:
		return json.Marshal(struct {
			Type  string      `json:"outcome"`
			Value HookBlocked `json:"value"`
		}{"Blocked", v.Value})
	case UserPromptSubmitOutcomeFailed:
		return json.Marshal(struct {
			Type  string     `json:"outcome"`
			Value HookFailed `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: UserPromptSubmitOutcome has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown UserPromptSubmitOutcome variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *UserPromptSubmitOutcome) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"outcome"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Ran":
		var v ContextInjected
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = UserPromptSubmitOutcomeRan{Value: v}
		return nil
	case "Blocked":
		var v HookBlocked
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = UserPromptSubmitOutcomeBlocked{Value: v}
		return nil
	case "Failed":
		var v HookFailed
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = UserPromptSubmitOutcomeFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown UserPromptSubmitOutcome variant tag %q", envelope.Type)
	}
}
