// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// An invocation about to be expanded. `command` is the matcher domain — the
// name, so a hook can guard `/deploy` rather than every prompt — and `kind`
// says which of `command`, `skill` or `agent` it named.
type UserPromptExpansionInput struct {
	Prompt  string `json:"prompt"`
	Command string `json:"command"`
	Kind    string `json:"kind"`
}
