// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// New user message — starts a new turn
type UserMessageInput struct {
	ID string `json:"id"`
	// May be empty: a turn started purely by owed subagent results carries
	// nothing the person typed.
	Text string `json:"text"`
	// Finished subagents' results delivered with this turn.
	SubagentResults []SubAgentResultPart `json:"subagentResults"`
}
