// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// How a velos vendor schedules containers.
type VelosVendorSettings struct {
	// The velos server root, e.g. `http://velos:8080`.
	ServerURL string `json:"serverUrl"`
	// OCI image bundling `horsie-runtime`, built without the sandbox feature —
	// the container is already the isolation boundary.
	Image string `json:"image"`
	// Path to `horsie-runtime` inside the image.
	RuntimeBin string `json:"runtimeBin"`
	// Where in the container workspaces are allocated.
	WorkspaceRoot string `json:"workspaceRoot"`
	// The `ws://` URL a container reaches this server on, *from velos's
	// container network* — not necessarily the address a browser uses.
	// Includes the connect path, as on a Fly vendor.
	CallbackURL string `json:"callbackUrl"`
	CPU         uint32 `json:"cpu"`
	MemoryMb    uint32 `json:"memoryMb"`
}
