// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The handshake was accepted: this agent is published under the name it
// announced, and sessions may select it from now on.
type VendorRegistered struct {
}
