// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// On the listed weekdays at `hour:minute` in `timezone`. At least one day;
// duplicates are rejected at save.
type WeeklySchedule struct {
	Timezone string    `json:"timezone"`
	Hour     uint32    `json:"hour"`
	Minute   uint32    `json:"minute"`
	Weekdays []Weekday `json:"weekdays"`
}
