// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Day of the week, Mon first — the order the UI renders.
type Weekday string

const (
	WeekdayMon Weekday = "Mon"
	WeekdayTue Weekday = "Tue"
	WeekdayWed Weekday = "Wed"
	WeekdayThu Weekday = "Thu"
	WeekdayFri Weekday = "Fri"
	WeekdaySat Weekday = "Sat"
	WeekdaySun Weekday = "Sun"
)
