// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Start a run: the configuration creating a session takes, plus the input the
// start step is handed.
type WorkflowRunRequest struct {
	Input string `json:"input"`
	// Runtime vendor for the run's single shared runtime; absent → the
	// server's default vendor at invoke.
	Vendor *string `json:"vendor,omitempty"`
	// Repositories cloned into the run's shared workspace.
	Repos *[]RepoConfig `json:"repos,omitempty"`
	// Optional run title.
	Name *string `json:"name,omitempty"`
}
