// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Start a run: the configuration creating a session takes, plus the input the
// start step is handed.
type WorkflowRunRequest struct {
	Input string `json:"input"`
	// Where the run's single shared runtime is built, and what it runs
	// against. Required.
	Environment EnvironmentSpec `json:"environment"`
	// Optional run title.
	Name *string `json:"name,omitempty"`
}
