// Code generated by fluorite. DO NOT EDIT.

package horsieapi

type WorkspaceScan struct {
	Name         string        `json:"name"`
	Path         string        `json:"path"`
	IsGitRepo    bool          `json:"isGitRepo"`
	Instructions *ScannedFile  `json:"instructions,omitempty"`
	Skills       []ScannedFile `json:"skills"`
	// Runtime OS/arch (`<os>-<arch>`, e.g. "macos-aarch64"); optional so an
	// older runtime binary still deserializes against a newer server.
	Platform *string `json:"platform,omitempty"`
}
