// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Create or fully replace a workflow. `description` defaults to "".
type WorkflowInput struct {
	Name        string            `json:"name"`
	Description *string           `json:"description,omitempty"`
	Start       string            `json:"start"`
	Steps       []WorkflowStepDef `json:"steps"`
	// Most step executions one run may perform before it is failed; at least 1.
	// Absent → the server's default.
	//
	// The only thing bounding a graph whose loop condition never flips, which
	// is why it lives on the definition rather than on the run request: the
	// budget is a property of the graph's shape, and a workflow that
	// legitimately loops twenty times knows that about itself.
	MaxSteps *uint32 `json:"maxSteps,omitempty"`
}
