// Code generated by fluorite. DO NOT EDIT.

package horsieapi

import (
	"encoding/json"
	"fmt"
)

// WorkflowStatusVariant is implemented by every variant of WorkflowStatus.
type WorkflowStatusVariant interface {
	isWorkflowStatusVariant()
}

type WorkflowStatusPending struct {
	Value PendingStatus
}

func (WorkflowStatusPending) isWorkflowStatusVariant() {}

type WorkflowStatusRunning struct {
	Value RunningStatus
}

func (WorkflowStatusRunning) isWorkflowStatusVariant() {}

type WorkflowStatusSuspended struct {
	Value SuspendedStatus
}

func (WorkflowStatusSuspended) isWorkflowStatusVariant() {}

type WorkflowStatusAwaitingInput struct {
	Value AwaitingInputStatus
}

func (WorkflowStatusAwaitingInput) isWorkflowStatusVariant() {}

type WorkflowStatusFinished struct {
	Value FinishedStatus
}

func (WorkflowStatusFinished) isWorkflowStatusVariant() {}

type WorkflowStatusFailed struct {
	Value FailedStatus
}

func (WorkflowStatusFailed) isWorkflowStatusVariant() {}

// Lifecycle of one run. `Suspended` means stopped part-way and resumable by
// retrying a step — cancelled, or a step interrupted by a restart. `Finished`
// carries the last step's output; `Failed` ended on an error no retry clears
// by itself.
// WorkflowStatus is an adjacently tagged union: its JSON carries the variant name
// in "type" and any payload in "value".
type WorkflowStatus struct {
	Variant WorkflowStatusVariant
}

// MarshalJSON encodes the set variant, or fails if none is set.
func (u WorkflowStatus) MarshalJSON() ([]byte, error) {
	switch v := u.Variant.(type) {
	case WorkflowStatusPending:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value PendingStatus `json:"value"`
		}{"Pending", v.Value})
	case WorkflowStatusRunning:
		return json.Marshal(struct {
			Type  string        `json:"type"`
			Value RunningStatus `json:"value"`
		}{"Running", v.Value})
	case WorkflowStatusSuspended:
		return json.Marshal(struct {
			Type  string          `json:"type"`
			Value SuspendedStatus `json:"value"`
		}{"Suspended", v.Value})
	case WorkflowStatusAwaitingInput:
		return json.Marshal(struct {
			Type  string              `json:"type"`
			Value AwaitingInputStatus `json:"value"`
		}{"AwaitingInput", v.Value})
	case WorkflowStatusFinished:
		return json.Marshal(struct {
			Type  string         `json:"type"`
			Value FinishedStatus `json:"value"`
		}{"Finished", v.Value})
	case WorkflowStatusFailed:
		return json.Marshal(struct {
			Type  string       `json:"type"`
			Value FailedStatus `json:"value"`
		}{"Failed", v.Value})
	case nil:
		return nil, fmt.Errorf("fluorite: WorkflowStatus has no variant set")
	default:
		return nil, fmt.Errorf("fluorite: unknown WorkflowStatus variant %T", v)
	}
}

// UnmarshalJSON decodes the tag, then the payload for the matching variant.
func (u *WorkflowStatus) UnmarshalJSON(data []byte) error {
	var envelope struct {
		Type  string          `json:"type"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return err
	}
	switch envelope.Type {
	case "Pending":
		var v PendingStatus
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = WorkflowStatusPending{Value: v}
		return nil
	case "Running":
		var v RunningStatus
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = WorkflowStatusRunning{Value: v}
		return nil
	case "Suspended":
		var v SuspendedStatus
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = WorkflowStatusSuspended{Value: v}
		return nil
	case "AwaitingInput":
		var v AwaitingInputStatus
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = WorkflowStatusAwaitingInput{Value: v}
		return nil
	case "Finished":
		var v FinishedStatus
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = WorkflowStatusFinished{Value: v}
		return nil
	case "Failed":
		var v FailedStatus
		if err := json.Unmarshal(envelope.Value, &v); err != nil {
			return err
		}
		u.Variant = WorkflowStatusFailed{Value: v}
		return nil
	default:
		return fmt.Errorf("fluorite: unknown WorkflowStatus variant tag %q", envelope.Type)
	}
}
