// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A workflow as shown to clients.
type WorkflowView struct {
	// Slug; the id of record, used in API paths.
	Name        string `json:"name"`
	Description string `json:"description"`
	// Name of the step every run begins at.
	Start string            `json:"start"`
	Steps []WorkflowStepDef `json:"steps"`
	// Most step executions one run may perform before it is failed. Absent →
	// the server's default.
	MaxSteps *uint32 `json:"maxSteps,omitempty"`
	// Unix epoch seconds.
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}
