// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// Re-run one step execution. The new attempt appends to the run log; earlier
// attempts are kept. A live run's current step is cancelled first.
type WorkflowRetryRequest struct {
	StepIndex uint32 `json:"stepIndex"`
}
