// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The session a run created. It is running by the time this is returned.
type WorkflowRunResponse struct {
	Session SessionSummary `json:"session"`
}
