// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// One step in a workflow graph.
type WorkflowStepDef struct {
	Name string `json:"name"`
	// Agent preset this step runs as.
	Agent string `json:"agent"`
	// The step's instruction. Whatever the step is handed — the run's input
	// for the start step, the previous step's output for every other — is
	// appended below it under a header.
	Prompt string `json:"prompt"`
	// JSON Schema for the step's structured output. When present, the step
	// finishes by calling the builtin terminal tool with output conforming to
	// it. Required when the step has any conditional transition, since there
	// would otherwise be nothing for the condition to read.
	OutputSchema *any `json:"outputSchema,omitempty"`
	// Outgoing transitions, evaluated against this step's output.
	Transitions *[]WorkflowTransition `json:"transitions,omitempty"`
	// Cap on agent-loop iterations for this step.
	MaxIterations *uint32 `json:"maxIterations,omitempty"`
	// Retry budget for transient provider errors within this step.
	MaxRetries *uint32 `json:"maxRetries,omitempty"`
}
