// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// The runtime working directory, resolved to `--working-dir` at apply time.
type WorkingDirGrant struct {
	Access Access `json:"access"`
}
