// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// A run, projected onto the definition's graph.
type WorkflowRunGraph struct {
	// The workflow this run was started from. The definition is snapshotted
	// at run creation, so editing or deleting it does not change this run.
	Workflow string `json:"workflow"`
	// Index into the run log of the execution in flight.
	Current *uint32   `json:"current,omitempty"`
	Start   string    `json:"start"`
	Nodes   []RunNode `json:"nodes"`
	Edges   []RunEdge `json:"edges"`
	// The last step's output, once the run has finished.
	Output *any    `json:"output,omitempty"`
	Error  *string `json:"error,omitempty"`
	// Every step's tokens, summed.
	InputTokens  uint32 `json:"inputTokens"`
	OutputTokens uint32 `json:"outputTokens"`
}
