// Code generated by fluorite. DO NOT EDIT.

package horsieapi

// On `month`/`day_of_month` every year in `timezone`. Invalid dates
// (Feb 29 in a non-leap year) recur only when valid.
type YearlySchedule struct {
	Timezone   string `json:"timezone"`
	Hour       uint32 `json:"hour"`
	Minute     uint32 `json:"minute"`
	Month      uint32 `json:"month"`
	DayOfMonth uint32 `json:"dayOfMonth"`
}
